import {test,expect} from '@playwright/test'
import {mkdirSync,writeFileSync} from 'node:fs'

test('prévia automática controla atualização, não gera PDF e mantém rascunho e guarda',async({page})=>{
 await page.goto('/tests/configuracoes/preview.html')
 await expect(page.getByText('Prévia atualizada',{exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:'Baixar PDF de demonstração'})).toHaveCount(0)
 const svg=page.getByRole('img',{name:'Prévia A4 da primeira página, com dados fictícios'})
 const atualizacoes=await svg.evaluate(e=>{(window as any).alteracoesPrevia=0;new MutationObserver(()=>{(window as any).alteracoesPrevia++}).observe(e,{childList:true,subtree:true,attributes:true});return 0})
 expect(atualizacoes).toBe(0)
 await page.getByRole('tab',{name:'Timbrados e documentos',exact:true}).click()
 const margem=page.getByLabel('Margens (mm)',{exact:true})
 for(const v of ['20','21','22','23'])await margem.fill(v)
 await expect.poll(()=>svg.locator('text').filter({hasText:'Demonstração de documento institucional'}).first().getAttribute('x')).toBe('23')
 expect(await page.evaluate(()=>(window as any).alteracoesPrevia)).toBeLessThanOrEqual(3)
 await page.getByLabel('Marca-d’água opcional',{exact:true}).fill('AÇÚCAR · DEMONSTRAÇÃO')
 await expect(svg.locator('text').filter({hasText:'AÇÚCAR · DEMONSTRAÇÃO'})).toBeVisible()
 await expect(page.getByRole('link',{name:'Baixar PDF de demonstração'})).toHaveCount(0)
 await expect(page.getByText('Alterações não salvas',{exact:true})).toBeVisible()
 await page.getByRole('tab',{name:'Dados da clínica',exact:true}).click()
 await page.getByRole('combobox',{name:'Alcance da edição',exact:true}).selectOption('22222222-2222-4222-8222-222222222222')
 await page.getByRole('alertdialog').getByRole('button',{name:'Continuar editando',exact:true}).click()
 await expect(page.getByText('Alterações não salvas',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Ajuda e integrações',exact:true}).click()
 await expect(page.getByText(/O PDF completo só é gerado pelo botão/)).toBeVisible()
 await page.screenshot({path:'scratch/configuracoes-revisao/editor-desktop.png',fullPage:true})
})

test('novo PDF explícito com logo fictícia, CNPJ, endereço e textos extensos; edição invalida download',async({page})=>{
 await page.goto('/tests/configuracoes/preview.html')
 await page.getByRole('tab',{name:'Identidade visual',exact:true}).click()
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=384;c.height=96;const ctx=c.getContext('2d')!;ctx.fillStyle='#006194';ctx.fillRect(0,8,80,80);ctx.fillStyle='white';ctx.fillRect(34,24,12,48);ctx.fillRect(16,42,48,12);ctx.fillStyle='#006194';ctx.font='bold 26px sans-serif';ctx.fillText('CLÍNICA EXEMPLO',96,60);return c.toDataURL('image/png').split(',')[1]})
 await page.getByLabel('Selecionar Logo principal',{exact:true}).setInputFiles({name:'logo-ficticia.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')})
 await page.getByRole('tab',{name:'Timbrados e documentos',exact:true}).click()
 await page.getByLabel('Posição da logo',{exact:true}).selectOption('center')
 await page.getByLabel('Alinhamento do texto',{exact:true}).selectOption('center')
 await page.getByRole('button',{name:'Adicionar linha',exact:true}).first().click()
 await page.getByLabel('Adicionar campo à linha 1 do Cabeçalho',{exact:true}).selectOption('cnpj')
 const cab=page.getByLabel('Texto complementar da linha 1 do Cabeçalho',{exact:true});await cab.fill('CNPJ DE TESTE · Atendimento fictício');await cab.press('Enter')
 const rod=page.getByLabel('Texto complementar da linha 1 do Rodapé',{exact:true});await rod.fill('Rodapé personalizado para conferir acentuação, espaçamento e identificação nas páginas.');await rod.press('Enter')
 await page.getByLabel('Marca-d’água opcional',{exact:true}).fill('DEMONSTRAÇÃO')
 await expect(page.locator('.cfg-papel image')).toBeVisible()
 expect(await page.locator('.cfg-papel image').evaluate(e=>Number(e.getAttribute('width'))/Number(e.getAttribute('height')))).toBe(4)
 await expect(page.getByRole('link',{name:'Baixar PDF de demonstração'})).toHaveCount(0)
 await page.getByRole('button',{name:'Gerar PDF de demonstração',exact:true}).click()
 const download=page.getByRole('link',{name:'Baixar PDF de demonstração'})
 await expect(download).toBeVisible();const d=page.waitForEvent('download');await download.click()
 mkdirSync('output/pdf',{recursive:true});await (await d).saveAs('output/pdf/demonstracao-configuracoes-revisada.pdf')
 await page.screenshot({path:'scratch/configuracoes-revisao/demonstracao-editor.png',fullPage:true})
 await page.getByLabel('Margens (mm)',{exact:true}).fill('22');await expect(download).toHaveCount(0)
})

test('conflito com fonte oficial exige confirmação, atualiza dados e conserva apresentação sem aplicar',async({page})=>{
 await page.goto('/tests/configuracoes/preview.html?conflito')
 await expect(page.getByText('Os dados oficiais mudaram',{exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'Aplicar configuração',exact:true})).toBeDisabled()
 await page.getByRole('button',{name:'Atualizar dados oficiais no rascunho',exact:true}).click()
 await expect(page.getByRole('alertdialog')).toContainText('sem aplicar')
 await page.getByRole('alertdialog').getByRole('button',{name:'Atualizar rascunho',exact:true}).click()
 await expect(page.getByLabel('Nome da unidade',{exact:true})).toHaveValue('Nome oficial atualizado')
 await expect(page.getByText('Os dados oficiais mudaram',{exact:true})).toHaveCount(0)
 await page.getByRole('tab',{name:'Timbrados e documentos',exact:true}).click()
 await expect(page.getByLabel('Margens (mm)',{exact:true})).toHaveValue('22')
 await page.getByRole('tab',{name:'Histórico de alterações',exact:true}).click()
 await expect(page.getByText('Versão 1 · rascunho',{exact:true})).toBeVisible()
})

test('falha da fonte não usa substituição silenciosa nem oferece PDF',async({page})=>{
 await page.route('**/NotoSans-*.ttf*',r=>r.fulfill({status:503,body:'Indisponibilidade sintética'}))
 await page.goto('/tests/configuracoes/preview.html')
 await expect(page.getByText('Prévia indisponível',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Gerar PDF de demonstração',exact:true}).click()
 await expect(page.getByText('Operação não concluída',{exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:'Baixar PDF de demonstração'})).toHaveCount(0)
})

test('medida fora dos limites impede prévia e geração explícita de PDF',async({page})=>{
 await page.goto('/tests/configuracoes/preview.html')
 await page.getByRole('tab',{name:'Timbrados e documentos',exact:true}).click()
 await page.getByLabel('Margens (mm)',{exact:true}).fill('0')
 await expect(page.getByText('Prévia indisponível',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Gerar PDF de demonstração',exact:true}).click()
 await expect(page.getByText('Operação não concluída',{exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:'Baixar PDF de demonstração'})).toHaveCount(0)
})

test('prévia A4 e ajuda recolhível cabem no celular escuro',async({page})=>{
 await page.setViewportSize({width:360,height:780});await page.goto('/tests/configuracoes/preview.html')
 await page.getByRole('button',{name:'Ativar modo escuro',exact:true}).click()
 await page.getByRole('button',{name:'Ir à prévia',exact:true}).click()
 await expect(page.locator('.cfg-papel')).toBeVisible()
 await page.evaluate(()=>document.fonts.ready)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(360)
 await page.screenshot({path:'scratch/configuracoes-revisao/editor-mobile.png',fullPage:true})
})

test('relatório financeiro existente conserva 180 linhas e totais com fonte incorporada',async({page})=>{
 await page.route('**/rest/v1/rpc/configuracoes_timbrado_consultar',r=>r.fulfill({headers:{'access-control-allow-origin':'*'},json:{instituicao:{nome:'Clínica Financeira Fictícia',nomeExibicao:'Clínica Financeira Fictícia',cidade:'Cidade Fictícia',empresaId:''},campos:{},geral:{},variacoes:{},versao:1,geralVersao:2,fonteRevisao:'fonte-financeira-sintetica'}}))
 await page.goto('/tests/configuracoes/preview.html')
 const arquivos=await page.evaluate(async()=>{
  const f=await import('/src/lib/financeiro/financeiro.relatorios.ts')
  const d=await import('/src/lib/timbradoPdf.ts'),c=await import('/supabase/functions/_shared/configuracoes.ts')
  const relatorio={titulo:'Relatório financeiro fictício',publico:'proprietaria',periodoInicio:'2026-10-01T03:00:00Z',periodoFim:'2026-10-09T03:00:00Z',timezone:'America/Bahia',geradoEm:'2026-10-08T21:00:00Z',clinicas:['Unidade fictícia'],filtros:[],metricas:[{rotulo:'Valor sintético',valor:'1234.56',tipo:'monetario'}],secoes:[{nomeAba:'Fictícios',titulo:'Movimentos fictícios',colunas:[{chave:'rotulo',titulo:'Movimento',tipo:'texto'},{chave:'valor',titulo:'Valor',tipo:'monetario'}],linhas:Array.from({length:180},(_,n)=>({rotulo:`Movimento fictício ${n+1}`,valor:'12.34'}))}]}
  const blob=await f.gerarPdfFinanceiroSobDemanda(relatorio,{clinicaId:'22222222-2222-4222-8222-222222222222'})
  const nome='Clínica Exemplo de Demonstração com Nome Institucional Longo '.repeat(3).trim()
  const s=c.criarSnapshot('sintetico',1,'padrao',{...c.instituicaoVazia(),nome,cidade:'Cidade Fictícia'},c.PADRAO)
  const unica=await d.gerarPdfTimbrado(s,[{texto:'Conferência de nome longo em negrito',titulo:true},{texto:'A quebra de linha deve conservar o texto dentro das margens.'}],true)
  return [Array.from(new Uint8Array(await blob.arrayBuffer())),Array.from(new Uint8Array(await unica.arrayBuffer()))]
 })
 writeFileSync('scratch/configuracoes-revisao/financeiro-revisado.pdf',Buffer.from(arquivos[0]))
 writeFileSync('scratch/configuracoes-revisao/nome-longo-revisado.pdf',Buffer.from(arquivos[1]))
 expect(arquivos.every(bytes=>bytes.length>1000)).toBe(true)
})
