-- APENAS fixture local. Auth/users/sessions abaixo são estruturas sintéticas;
-- nenhuma senha, login real, pessoa ou conta do Supabase é criada.
begin;
do $$
declare
 ator uuid:='11111111-1111-4111-8111-111111111111';
 membro uuid:='22222222-2222-4222-8222-222222222222';
 ca uuid:='33333333-3333-4333-8333-333333333333';
 cb uuid:='44444444-4444-4444-8444-444444444444';
 chave uuid:='55555555-5555-4555-8555-555555555555';
 sessao uuid:='66666666-6666-4666-8666-666666666666';
 verificada uuid:='77777777-7777-4777-8777-777777777777';
 nova uuid:='88888888-8888-4888-8888-888888888888';
 escopos jsonb; r jsonb; o acesso_direto.operacoes%rowtype; negado boolean; total integer;
begin
 insert into public.usuarios values(ator,'Administradora sintética',true);
 insert into public.clinicas values(ca,true),(cb,true);
 insert into public.usuarios_clinicas values(ator,ca,'proprietaria',true),(ator,cb,'proprietaria',true);
 insert into public.equipe_membros values(membro,null,'Membro sintético',true);
 insert into public.equipe_membros_clinicas values(membro,ca,true),(membro,cb,true);
 escopos:=jsonb_build_array(jsonb_build_object('clinica_id',ca,'papel','medico'),jsonb_build_object('clinica_id',cb,'papel','recepcao'));
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ator,'role','authenticated')::text,true);
 if not public.acesso_direto_sessao_permitida() or public.acesso_direto_estado()->>'estado'<>'normal' then raise exception 'Conta antiga indevidamente bloqueada'; end if;
 perform set_config('request.path','/rpc/graphql',true);
 perform public.acesso_direto_pre_request();
 raise notice 'PASS conta sem operação preservada';
 negado:=false;
 begin perform public.acesso_direto_reservar(ator,membro,ca,'um@acesso-direto.example.invalid',escopos,chave); exception when others then negado:=sqlerrm='SERVICO_INDISPONIVEL'; end;
 if not negado then raise exception 'Flag desligada não bloqueou'; end if;
 insert into acesso_direto.homologacao values(membro,ator,'um@acesso-direto.example.invalid');
 update acesso_direto.controle set homologacao_habilitada=true;
 negado:=false;
 begin perform public.acesso_direto_reservar(ator,membro,ca,'outro@acesso-direto.example.invalid',escopos,chave); exception when others then negado:=sqlerrm='SERVICO_INDISPONIVEL'; end;
 if not negado then raise exception 'Homologação aceitou email fora da lista'; end if;
 raise notice 'PASS flags e homologação limitada ao email/pessoa/ator';
 negado:=false;
 begin perform acesso_direto.autorizar(ator,membro,ca,'[{"clinica_id":null,"papel":null}]'); exception when sqlstate '22023' then negado:=true; end;
 if not negado then raise exception 'Papel nulo aceito'; end if;
 update public.usuarios_clinicas set ativo=false where usuario_id=ator and clinica_id=cb;
 negado:=false;
 begin perform public.acesso_direto_reservar(ator,membro,ca,'um@acesso-direto.example.invalid',escopos,chave); exception when sqlstate '42501' then negado:=true; end;
 if not negado then raise exception 'Admin sem escopo B aceito'; end if;
 update public.usuarios_clinicas set ativo=true where usuario_id=ator and clinica_id=cb;
 raise notice 'PASS papel explícito e autorização em todas as clínicas';
 r:=public.acesso_direto_reservar(ator,membro,ca,'um@acesso-direto.example.invalid',escopos,chave);
 select * into o from acesso_direto.operacoes where id=(r->>'id')::uuid;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',o.auth_user_id,'role','authenticated','session_id',sessao)::text,true);
 if public.acesso_direto_sessao_permitida() then raise exception 'Reserva concedeu acesso antes do Auth'; end if;
 raise notice 'PASS reserva bloqueia antes da criação Auth';
 insert into auth.users values(o.auth_user_id,o.email,'FINGERPRINT_TEMP_SINTETICO',jsonb_build_object('acesso_direto_operacao',o.id));
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 perform public.acesso_direto_confirmar_conta(o.id,o.reserva_id,repeat('a',64));
 if exists(select 1 from public.usuarios_clinicas where usuario_id=o.auth_user_id and ativo) then raise exception 'Vínculo ativado antes da troca'; end if;
 negado:=false; begin update public.usuarios_clinicas set ativo=true where usuario_id=o.auth_user_id; exception when sqlstate '42501' then negado:=true; end;
 if not negado then raise exception 'Caminho administrativo antigo concedeu vínculo pendente'; end if;
 insert into auth.sessions values(sessao,o.auth_user_id,clock_timestamp());
 insert into public.dados_teste values(1);
 insert into storage.objects values(1);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',o.auth_user_id,'role','authenticated','session_id',sessao)::text,true);
 execute 'set local role authenticated';
 perform set_config('request.path','/rpc/graphql',true);
 negado:=false; begin perform public.acesso_direto_pre_request(); exception when sqlstate '42501' then negado:=true; end;
 if not negado then raise exception 'Pre-request GraphQL não bloqueou pendência'; end if;
 perform set_config('request.path','/dados_teste',true);
 negado:=false; begin perform public.acesso_direto_pre_request(); exception when sqlstate '42501' then negado:=true; end;
 if not negado then raise exception 'Pre-request REST não bloqueou pendência'; end if;
 perform set_config('request.path','/rpc/acesso_direto_estado',true);
 perform public.acesso_direto_pre_request();
 if public.acesso_direto_estado()->>'estado'<>'pendente' then raise exception 'Estado necessário ao primeiro acesso foi bloqueado'; end if;
 select count(*) into total from public.dados_teste;
 if total<>0 then raise exception 'RLS não bloqueou'; end if;
 select count(*) into total from storage.objects;
 if total<>0 then raise exception 'Storage não bloqueou'; end if;
 negado:=false; begin perform public.rpc_sql_teste(); exception when sqlstate '42501' then negado:=true; end;
 if not negado then raise exception 'RPC SQL liberada'; end if;
 negado:=false; begin perform public.rpc_plpgsql_teste(); exception when sqlstate '42501' then negado:=true; end;
 if not negado then raise exception 'RPC PLPGSQL liberada'; end if;
 negado:=false; begin perform graphql_public.rpc_teste(); exception when sqlstate '42501' then negado:=true; end;
 if not negado then raise exception 'GraphQL liberado'; end if;
 execute 'reset role';
 if has_function_privilege('authenticated','public.acesso_direto_concluir_troca(uuid,uuid)','EXECUTE') or has_table_privilege('authenticated','acesso_direto.operacoes','UPDATE') or has_schema_privilege('authenticated','acesso_direto','USAGE') then raise exception 'Usuário pode retirar pendência'; end if;
 raise notice 'PASS RLS, Storage, RPC SQL/PLPGSQL, GraphQL e ACL administrativa';
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 r:=public.acesso_direto_reservar_troca(o.auth_user_id,sessao);
 select * into o from acesso_direto.operacoes where id=o.id;
 update auth.users set encrypted_password='FINGERPRINT_PESSOAL_SINTETICO' where id=o.auth_user_id;
 negado:=false; begin perform public.acesso_direto_concluir_troca(o.id,o.reserva_id); exception when others then negado:=sqlerrm='CONFLITO'; end;
 if not negado then raise exception 'Só alteração de hash retirou pendência'; end if;
 perform public.acesso_direto_preparar_verificacao(o.id,o.reserva_id);
 insert into auth.sessions values(verificada,o.auth_user_id,clock_timestamp());
 perform public.acesso_direto_registrar_verificacao(o.id,o.reserva_id,verificada);
 update auth.users set encrypted_password='FINGERPRINT_CONCORRENTE_SINTETICO' where id=o.auth_user_id;
 negado:=false; begin perform public.acesso_direto_concluir_troca(o.id,o.reserva_id); exception when others then negado:=sqlerrm='CONFLITO'; end;
 if not negado then raise exception 'Alteração concorrente liberada'; end if;
 update auth.users set encrypted_password='FINGERPRINT_PESSOAL_SINTETICO' where id=o.auth_user_id;
 negado:=false; begin perform public.acesso_direto_concluir_troca(o.id,o.reserva_id); exception when others then negado:=sqlerrm='CONFLITO'; end;
 if not negado then raise exception 'Revogação global não verificada'; end if;
 delete from auth.sessions where user_id=o.auth_user_id;
 raise notice 'PASS atualização sem prova, concorrência e ausência de revogação recusadas';
 perform public.acesso_direto_concluir_troca(o.id,o.reserva_id);
 -- Defesa adicional mesmo se um registro antigo sobrevivesse à revogação.
 insert into auth.sessions values(sessao,o.auth_user_id,clock_timestamp()-interval '1 minute');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',o.auth_user_id,'role','authenticated','session_id',sessao)::text,true);
 if public.acesso_direto_sessao_permitida() then raise exception 'Sessão antiga ganhou acesso após ativação'; end if;
 if public.acesso_direto_estado()->>'estado'<>'sessao_obsoleta' then raise exception 'Estado antigo incorreto'; end if;
 perform set_config('request.path','/rpc/graphql',true);
 negado:=false; begin perform public.acesso_direto_pre_request(); exception when sqlstate '42501' then negado:=true; end;
 if not negado then raise exception 'Pre-request liberou sessão temporária antiga'; end if;
 raise notice 'PASS sessão temporária antiga continua bloqueada após ativação';
 insert into auth.sessions values(nova,o.auth_user_id,clock_timestamp());
 perform set_config('request.jwt.claims',jsonb_build_object('sub',o.auth_user_id,'role','authenticated','session_id',nova)::text,true);
 if not public.acesso_direto_sessao_permitida() then raise exception 'Sessão nova bloqueada'; end if;
 perform public.acesso_direto_pre_request();
 execute 'set local role authenticated';
 select count(*) into total from public.dados_teste;
 if total<>1 or public.rpc_sql_teste()<>7 or public.rpc_plpgsql_teste()<>7 or graphql_public.rpc_teste()<>7 then raise exception 'Regressão da sessão nova'; end if;
 execute 'reset role';
 update acesso_direto.controle set homologacao_habilitada=false;
 if not public.acesso_direto_sessao_permitida() then raise exception 'Desabilitar criação bloqueou sessão já ativa'; end if;
 if (select habilitado from acesso_direto.controle where id) then raise exception 'Teste habilitou flag geral'; end if;
 raise notice 'PASS sessão nova acessa; flag geral nunca habilitada';
 update acesso_direto.operacoes set estado='pendente',expira_em=clock_timestamp()-interval '1 second' where id=o.id;
 if public.acesso_direto_sessao_permitida() then raise exception 'Expiração liberou dados'; end if;
 if not (public.acesso_direto_token_hook(jsonb_build_object('user_id',o.auth_user_id,'claims',jsonb_build_object('session_id',nova))) ? 'error') then raise exception 'Hook não recusou expiração'; end if;
 update acesso_direto.operacoes set estado='substituindo' where id=o.id;
 if public.acesso_direto_sessao_permitida() then raise exception 'Substituição parcial liberou'; end if;
 raise notice 'PASS expiração e substituição parcial bloqueadas';
end $$;
rollback;
