import test from 'node:test'
import assert from 'node:assert/strict'
import {PADRAO,instituicaoVazia,resolverApresentacao,resolverTipoDocumento,voltarAoPadrao,validarDocumento,validarPersonalizacao,comporLinhas,criarSnapshot,contrasteBranco} from '../../supabase/functions/_shared/configuracoes.ts'
test('herança por campo conserva vazio, false e lista vazia; retorno remove somente override',()=>{const a=resolverApresentacao({loginMensagem:'Geral',paginas:true},{loginMensagem:'',paginas:false,rodape:[]});assert.equal(a.loginMensagem,'');assert.equal(a.paginas,false);assert.deepEqual(a.rodape,[]);assert.equal(resolverApresentacao({loginMensagem:'Geral'},voltarAoPadrao({loginMensagem:''},'loginMensagem')).loginMensagem,'Geral')})
test('logo principal é alternativa apenas na ausência de escolha; vazio explícito remove logo específica',()=>{assert.equal(resolverApresentacao({},{logoPrincipal:'principal'}).loginLogo,'principal');assert.equal(resolverApresentacao({},{logoPrincipal:'principal',loginLogo:''}).loginLogo,'');assert.equal(resolverApresentacao({logoImpressao:''},{logoPrincipal:'principal'}).logoImpressao,'')})
test('variação herda unidade e não afeta padrão',()=>{const u={...PADRAO,margem:22};assert.equal(resolverApresentacao({},u,{logoPosicao:'right'}).margem,22);assert.equal(u.logoPosicao,'left')})
test('variação geral respeita personalização da unidade e vazio específico do tipo',()=>{const g={relatorio_financeiro:{marcaDagua:'Geral financeiro',margem:22}};const a=resolverTipoDocumento({margem:18},g,{margem:20},{relatorio_financeiro:{marcaDagua:''}},'relatorio_financeiro');assert.equal(a.margem,20);assert.equal(a.marcaDagua,'');assert.equal(resolverTipoDocumento({},g,{},{},'relatorio_financeiro').marcaDagua,'Geral financeiro');assert.equal(resolverTipoDocumento({},g,{},{},'padrao').marcaDagua,'')})
test('padrão geral rejeita identidade jurídica',()=>{assert.throws(()=>validarDocumento({instituicao:instituicaoVazia(),campos:{},variacoes:{}},true),/jurídica/);assert.equal(validarDocumento({instituicao:null,campos:{},variacoes:{}},true).instituicao,null)})
test('unidade incompleta legítima é aceita sem fabricar CNPJ; nome/cidade seguem obrigatórios',()=>{const d={instituicao:{...instituicaoVazia(),nome:'Unidade',cidade:'Cidade'},campos:{},variacoes:{}};assert.equal(validarDocumento(d).instituicao?.cnpj,'');assert.throws(()=>validarDocumento({...d,instituicao:instituicaoVazia()}),/nome.*cidade/)})
test('scripts, HTML, variáveis desconhecidas, caminhos executáveis e atributos extras recusados',()=>{for(const campos of [{loginMensagem:'<script>x</script>'},{cabecalho:[[{campo:'cpf'}]]},{logoPrincipal:'https://evil.invalid/x.svg'},{rodape:[[{texto:'ok',html:'x'}]]},{admin:true}])assert.throws(()=>validarPersonalizacao(campos))})
test('limites de geometria e contraste garantem área útil legível',()=>{assert.ok(contrasteBranco('#006194')>=4.5);for(const c of [{cor:'#FFFFFF'},{cor:'red'},{margem:0},{espaco:30},{logoLargura:200},{loginFocoX:-1}])assert.throws(()=>validarPersonalizacao(c))})
test('dados jurídicos inválidos e URLs inseguras são recusados',()=>{const i={...instituicaoVazia(),nome:'Unidade',cidade:'Cidade'};for(const patch of [{cnpj:'00000000000000'},{cep:'123'},{uf:'XX'},{telefone:'123'},{email:'invalido'},{site:'javascript:alert(1)'}])assert.throws(()=>validarDocumento({instituicao:{...i,...patch},campos:{},variacoes:{}}))})
test('snapshot e campos do emissor são independentes de alteração posterior',()=>{const i={...instituicaoVazia(),nome:'Unidade',razaoSocial:'Emissor',cnpj:'',cidade:'Cidade'};const s=criarSnapshot('unidade',2,'padrao',i,PADRAO);i.nome='Alterada';PADRAO.loginMensagem='nova';assert.equal(s.instituicao.nome,'Unidade');assert.equal(s.apresentacao.loginMensagem,'');PADRAO.loginMensagem='';assert.deepEqual(comporLinhas([[{campo:'razaoSocial'},{campo:'cnpj'}]],s.instituicao),['Emissor'])})
