import { expect, test, type Page } from '@playwright/test'
import { filtrarProfissionalAgenda } from './agenda-test-utils'

const previa = '/tests/operacional/agenda-preview.html'
const pasta = 'scratch/agenda-ux/celular'
const hoje = (() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` })()
async function abrir(page: Page, query = '', hora = '06:00') {
  await page.clock.setFixedTime(new Date(`${hoje}T${hora}:00`))
  await page.goto(`${previa}?${query}`, { waitUntil: 'domcontentloaded' })
  await expect(page.getByTestId('registro-agenda').first()).toBeAttached({ timeout: 30_000 })
  await page.getByRole('button', { name: 'Lista', exact: true }).click()
}
async function semOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
}
async function captar(page: Page, nome: string) {
  await page.screenshot({ path: `${pasta}/${nome}.png`, animations: 'disabled' })
}
test.beforeEach(() => test.setTimeout(60_000))

for (const tamanho of [{ width: 390, height: 844 }, { width: 360, height: 740 }]) {
  test(`celular ${tamanho.width}: Todos, chips, livres e painel preenchido sem envio`, async ({ page }, info) => {
    test.skip(info.project.name !== 'mobile', 'Dimensões móveis explícitas.')
    await page.setViewportSize(tamanho)
    await abrir(page, 'celular')
    await expect(page.getByTestId('registro-agenda')).toHaveCount(6)
    await expect(page.locator('.agenda-celular-livre')).toHaveCount(0)
    await expect(page.locator('.agenda-celular-dias button')).toHaveCount(5)
    await expect(page.locator('.agenda-lista-linha time')).toHaveText(['08:00', '08:30', '09:00', '09:30', '10:30', '11:00'])
    await expect(page.locator('.agenda-lista-linha[data-situacao="em-atendimento"]')).toContainText('Em atendimento')
    await expect(page.locator('.agenda-lista-linha[data-situacao="concluido"]')).toContainText('Concluído')
    for (const rect of await page.locator('.agenda-lista-acoes button').evaluateAll(els => els.map(el => ({ h: el.getBoundingClientRect().height, w: el.getBoundingClientRect().width })))) {
      expect(rect.h).toBeGreaterThanOrEqual(44); expect(rect.w).toBeGreaterThanOrEqual(44)
    }
    await semOverflow(page)
    await captar(page, `todos-${tamanho.width}`)
    await filtrarProfissionalAgenda(page, 'prof-1')
    await expect(page.getByRole('button', { name: 'Horário livre às 10:00 — agendar', exact: true })).toBeVisible()
    await expect(page.getByTestId('registro-agenda')).toHaveCount(6)
    await semOverflow(page)
    await captar(page, `profissional-livres-${tamanho.width}`)
    await page.locator('.agenda-celular-lista').screenshot({ path: `${pasta}/linha-do-tempo-${tamanho.width}.png`, animations: 'disabled' })
    const livre = page.getByRole('button', { name: 'Horário livre às 10:00 — agendar', exact: true })
    await livre.press('Enter')
    const painel = page.getByRole('dialog', { name: 'Novo agendamento' })
    await expect(painel.locator('input[name="novo-agendamento-profissional"][value="prof-1"]')).toBeChecked()
    await expect(painel.getByRole('group', { name: 'Resumo do horário' })).toContainText('10:00–10:30')
    await expect(painel.getByLabel('Outra data')).toHaveValue(hoje)
    await expect(page.locator('html')).not.toHaveAttribute('data-envios-sinteticos', /.+/)
    await expect(page.locator('.agenda-celular-novo')).toHaveCount(0)
    await captar(page, `livre-painel-${tamanho.width}`)
  })
  test(`celular ${tamanho.width}: datas, último cartão, sem expediente, escuro e Ipupiara`, async ({ page }, info) => {
    test.skip(info.project.name !== 'mobile', 'Dimensões móveis explícitas.')
    await page.setViewportSize(tamanho)
    await abrir(page, 'celular')
    const dias = page.getByRole('group', { name: 'Dias da agenda no celular' }).getByRole('button')
    const rotulos = await dias.allTextContents()
    await dias.nth(1).click()
    await expect(dias.nth(1)).toHaveAttribute('aria-pressed', 'true')
    expect(await dias.allTextContents()).toEqual(rotulos)
    await expect(page.getByTestId('registro-agenda')).toHaveCount(0)
    await page.getByRole('button', { name: 'Hoje', exact: true }).click()
    await expect(page.getByTestId('registro-agenda')).toHaveCount(6)
    // Espaço de rolagem permite posicionar integralmente o último cartão acima do botão fixo.
    await page.getByTestId('registro-agenda').last().evaluate(el => el.scrollIntoView({ block: 'center' }))
    const ultimo = (await page.getByTestId('registro-agenda').last().boundingBox())!
    const rodape = (await page.locator('.agenda-celular-novo').boundingBox())!
    expect(ultimo.y).toBeGreaterThanOrEqual(0)
    expect(ultimo.y + ultimo.height).toBeLessThanOrEqual(rodape.y)
    await captar(page, `ultimo-item-${tamanho.width}`)
    await abrir(page, 'celular&sem-expediente')
    await filtrarProfissionalAgenda(page, 'prof-1')
    await expect(page.locator('.agenda-celular-livre')).toHaveCount(0)
    await expect(page.getByTestId('registro-agenda')).toHaveCount(6)
    await expect(page.getByTestId('registro-agenda').first()).toContainText('Sem expediente')
    await semOverflow(page)
    await captar(page, `sem-expediente-${tamanho.width}`)
    await page.getByRole('button', { name: 'Alternar tema', exact: true }).click()
    await captar(page, `escuro-brotas-${tamanho.width}`)
    await abrir(page, 'celular&unidade=ipupiara')
    await filtrarProfissionalAgenda(page, 'prof-1')
    await semOverflow(page)
    await captar(page, `ipupiara-${tamanho.width}`)
    await page.getByRole('button', { name: 'Alternar tema', exact: true }).click()
    await semOverflow(page)
    await captar(page, `escuro-ipupiara-${tamanho.width}`)
  })
}

test('celular: Médico sem ações de recepção; acima de oito profissionais mantém select', async ({ page }, info) => {
  test.skip(info.project.name !== 'mobile', 'Composição móvel.')
  await abrir(page, 'celular&papel=medico')
  await expect(page.getByRole('button', { name: 'Registrar chegada', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Editar agendamento', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '+ Novo agendamento', exact: true })).toHaveCount(0)
  await abrir(page, 'nove-profissionais')
  await expect(page.getByLabel('Filtrar profissional')).toBeVisible()
  await expect(page.getByRole('group', { name: 'Profissionais no celular' })).toHaveCount(0)
  await semOverflow(page)
})

test('B1: faixa e blocos ignoram o próprio registro, criação continua contando os três ocupados', async ({ page }, info) => {
  await abrir(page, 'remarcacao')
  await page.locator('[data-registro-id="ag-r"]').getByRole('button', { name: 'Editar agendamento' }).click()
  const painel = page.getByRole('dialog', { name: 'Remarcar agendamento' })
  await expect(painel.getByRole('group', { name: 'Próximos dias' }).getByRole('button').first()).toContainText('18 livres')
  const livres = painel.getByRole('group', { name: 'Horários disponíveis', exact: true }).getByRole('button').filter({ hasNot: page.locator('[disabled]') })
  expect(await livres.evaluateAll(els => els.filter(el => !(el as HTMLButtonElement).disabled).length)).toBe(18)
  await expect(painel.getByRole('group', { name: 'Horários disponíveis', exact: true }).getByRole('button', { name: '11:00', exact: true })).toBeEnabled()
  await painel.getByRole('group', { name: 'Próximos dias' }).scrollIntoViewIfNeeded()
  await captar(page, `b1-${info.project.name}`)
  await abrir(page, 'remarcacao')
  await page.getByRole('button', { name: '+ Novo agendamento', exact: true }).click()
  const novo = page.getByRole('dialog', { name: 'Novo agendamento' })
  await novo.locator('input[name="novo-agendamento-profissional"][value="prof-1"]').check()
  await expect(novo.getByRole('group', { name: 'Próximos dias' }).getByRole('button').first()).toContainText('17 livres')
})

test('B2: passados desabilitados, faixa e indicador coerentes; futuro intacto e Outro horário preservado', async ({ page }, info) => {
  await abrir(page, '', '10:20')
  await expect(page.getByRole('region', { name: 'Resumo do dia' }).locator(':scope > div').nth(3)).toContainText('15')
  await page.getByRole('button', { name: 'Dia', exact: true }).click()
  await expect(page.getByRole('button', { name: '08:00 horário já passou — Profissional Sintético — Clínica geral', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '+ Novo agendamento', exact: true }).click()
  const painel = page.getByRole('dialog', { name: 'Novo agendamento' })
  await painel.locator('input[name="novo-agendamento-profissional"][value="prof-1"]').check()
  const faixa = painel.getByRole('group', { name: 'Próximos dias' })
  await expect(faixa.getByRole('button').first()).toContainText('15 livres')
  const blocos = painel.getByRole('group', { name: 'Horários disponíveis', exact: true })
  const passado = blocos.getByRole('button', { name: '08:00 horário já passou', exact: true })
  await expect(passado).toBeDisabled()
  await expect(passado).toHaveCSS('opacity', '0.5')
  await expect(blocos.getByRole('button', { name: '10:00 horário já passou', exact: true })).toBeDisabled()
  await expect(blocos.getByRole('button', { name: '10:30', exact: true })).toBeEnabled()
  await faixa.scrollIntoViewIfNeeded()
  await captar(page, `b2-${info.project.name}`)
  await passado.scrollIntoViewIfNeeded()
  await captar(page, `b2-blocos-${info.project.name}`)
  await painel.getByRole('button', { name: 'Outro horário', exact: true }).click()
  await painel.getByLabel('Início', { exact: true }).fill('08:00')
  await expect(painel.getByLabel('Início', { exact: true })).toHaveValue('08:00')
  await faixa.getByRole('button').nth(1).click()
  await expect(faixa.getByRole('button').nth(1)).toContainText('20 livres')
  await expect(blocos.getByRole('button', { name: '08:00', exact: true })).toBeEnabled()
})
