
// Painel de criação: cartões de profissional (rádios nativos) ou select acima de seis.
const radioProfissional = (escopo: Page | Locator, id: string) => escopo.locator(`input[name="novo-agendamento-profissional"][value="${id}"]`)
const pacienteEscolhido = (escopo: Page | Locator) => escopo.getByRole('group', { name: 'Paciente selecionado' })
import { expect, test, type Locator, type Page } from '@playwright/test'

// Interface real com serviços sintéticos do harness. Não é autenticação nem banco real.
const previa = '/tests/operacional/agenda-preview.html'
test.beforeEach(() => test.setTimeout(90_000))
async function abrir(page: Page, query = '') {
  await page.goto(previa + query, { waitUntil: 'domcontentloaded' })
  await expect(page.getByTestId('registro-agenda')).toHaveCount(3)
  // Computador abre no modo Dia; estes cenários usam as ações da lista.
  await page.getByRole('button', { name: 'Lista', exact: true }).click()
}
async function semOverflow(page: Page) {
  const medidas = await page.evaluate(() => ({ largura: document.documentElement.scrollWidth, viewport: innerWidth }))
  expect(medidas.largura).toBeLessThanOrEqual(medidas.viewport + 1)
}

for (const unidade of ['brotas', 'ipupiara']) {
  test(`lista e grade ${unidade}: mesmos registros, ordem, filtros e separação da espera`, async ({ page }, info) => {
    await abrir(page, `?unidade=${unidade}&sem-expediente`)
    await expect(page.getByRole('button', { name: 'Lista', exact: true })).toHaveAttribute('aria-pressed', 'true')
    const lista = await page.getByTestId('registro-agenda').allTextContents()
    expect(lista.map(s => s.match(/\d{2}:\d{2}/)?.[0])).toEqual(['09:00', '10:00', '16:00'])
    await expect(page.getByRole('region', { name: 'Lista de espera' })).toContainText('Davi Exemplo Sintético')
    await expect(page.getByRole('region', { name: 'Agendamentos do dia' })).not.toContainText('Davi Exemplo Sintético')
    await semOverflow(page)
    if (unidade === 'brotas') await page.screenshot({ path: `scratch/agenda-ux/lista-${info.project.name}.png`, fullPage: true })
    await page.getByRole('button', { name: 'Dia', exact: true }).click()
    expect((await page.getByTestId('registro-agenda').evaluateAll(nodes => nodes.map(n => n.getAttribute('data-registro-id')))).sort()).toEqual(['ag-1', 'ag-2', 'ag-3'])
    await semOverflow(page)
    if (unidade === 'brotas') await page.screenshot({ path: `scratch/agenda-ux/grade-${info.project.name}.png`, fullPage: true })
    await page.getByLabel('Filtrar profissional').selectOption('prof-2')
    await expect(page.getByTestId('registro-agenda')).toHaveCount(1)
    await expect(page.getByTestId('registro-agenda')).toContainText('Clara Exemplo Sintético')
    await page.getByRole('button', { name: 'Lista', exact: true }).click()
    await expect(page.getByTestId('registro-agenda')).toHaveCount(1)
    await page.getByLabel('Filtrar profissional').selectOption('')
    await page.getByLabel('Busca na Agenda').fill('Bruno')
    await expect(page.getByTestId('registro-agenda')).toHaveCount(1)
  })
}

test('seleção explícita por teclado, criação manual e confirmação fora do painel', async ({ page }, info) => {
  await abrir(page)
  await page.getByRole('button', { name: '+ Novo agendamento', exact: true }).click()
  const painel = page.getByRole('dialog', { name: 'Novo agendamento' })
  const paciente = painel.getByRole('combobox', { name: 'Paciente', exact: true })
  await paciente.fill('Ana')
  await expect(pacienteEscolhido(painel)).toHaveCount(0)
  await paciente.press('Enter')
  await expect(pacienteEscolhido(painel)).toContainText('Ana Exemplo Sintético')
  await radioProfissional(painel, 'prof-2').check()
  await painel.getByRole('button', { name: 'Outro horário', exact: true }).click()
  await painel.getByLabel(/^Início/).fill('11:00')
  await painel.getByLabel('Observações').fill('Observação exclusivamente sintética')
  await expect(painel).toContainText('Sem expediente cadastrado')
  await expect(painel.getByLabel('Resumo do horário')).toContainText('11:40')
  await expect(painel.getByRole('button', { name: 'Agendar', exact: true })).toBeDisabled()
  await painel.getByRole('checkbox', { name: /confirmo a marcação manual/ }).check()
  await expect(painel.getByRole('button', { name: 'Agendar', exact: true })).toBeEnabled()
  const botao = await painel.getByRole('button', { name: 'Agendar', exact: true }).boundingBox()
  expect(botao!.y + botao!.height).toBeLessThanOrEqual(page.viewportSize()!.height)
  const geometria = await painel.boundingBox()
  if (info.project.name === 'mobile') expect(geometria!.width).toBe(page.viewportSize()!.width)
  await semOverflow(page)
  await page.screenshot({ path: `scratch/agenda-ux/criacao-${info.project.name}.png` })
  await painel.getByRole('button', { name: 'Agendar', exact: true }).click()
  await expect(painel).toHaveCount(0)
  await expect(page.getByRole('status').filter({ hasText: 'Agendamento criado' })).toBeVisible()
  await expect(page.getByTestId('registro-agenda')).toHaveCount(4)
  await expect(page.getByTestId('registro-agenda').filter({ hasText: '11:00' })).toContainText('Ana Exemplo Sintético')
})

test('edição em painel, rodapé visível e sucesso sem duplicação; tema escuro', async ({ page }, info) => {
  await abrir(page)
  await page.getByTestId('registro-agenda').filter({ hasText: 'Clara Exemplo' }).getByRole('button', { name: 'Editar agendamento' }).click()
  const painel = page.getByRole('dialog', { name: 'Editar agendamento' })
  await painel.getByLabel('Novo horário', { exact: true }).fill('16:40')
  await painel.getByLabel('Motivo da correção').fill('Correção sintética para conferir a interface')
  await painel.getByRole('checkbox', { name: /Conferi o horário/ }).check()
  await expect(painel.getByRole('button', { name: 'Salvar alterações' })).toBeEnabled()
  await expect(painel.getByLabel('Resumo do horário')).toContainText('17:20')
  const botao = await painel.getByRole('button', { name: 'Salvar alterações' }).boundingBox()
  expect(botao!.y + botao!.height).toBeLessThanOrEqual(page.viewportSize()!.height)
  await semOverflow(page)
  await page.screenshot({ path: `scratch/agenda-ux/edicao-${info.project.name}.png` })
  await painel.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(painel).toHaveCount(0)
  await expect(page.getByRole('status').filter({ hasText: 'Agendamento atualizado' })).toHaveCount(1)
  await expect(page.getByTestId('registro-agenda').filter({ hasText: 'Clara Exemplo' })).toContainText('16:40–17:20')
  await expect(page.getByTestId('registro-agenda')).toHaveCount(3)
  await page.getByRole('button', { name: 'Alternar tema' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'escuro')
  await page.getByTestId('registro-agenda').filter({ hasText: 'Clara Exemplo' }).getByRole('button', { name: 'Editar agendamento' }).click()
  await semOverflow(page)
  await page.screenshot({ path: `scratch/agenda-ux/edicao-escuro-${info.project.name}.png` })
  await page.keyboard.press('Escape')
  await expect(painel).toHaveCount(0)
})

test('falha de leitura não esconde os registros nem autoriza marcação manual', async ({ page }) => {
  await abrir(page, '?falha')
  await expect(page.getByRole('alert')).toContainText('Isso não significa ausência de expediente')
  await expect(page.getByTestId('registro-agenda').first()).toContainText('Disponibilidade não confirmada')
  await page.getByRole('button', { name: '+ Novo agendamento', exact: true }).click()
  const painel = page.getByRole('dialog', { name: 'Novo agendamento' })
  await painel.getByRole('combobox', { name: 'Paciente', exact: true }).fill('Ana')
  await painel.getByRole('option', { name: 'Ana Exemplo Sintético' }).click()
  await radioProfissional(painel, 'prof-2').check()
  await painel.getByRole('button', { name: 'Outro horário', exact: true }).click()
  await painel.getByLabel(/^Início/).fill('11:00')
  await expect(painel.getByRole('alert')).toContainText('Falha ao consultar disponibilidade')
  await expect(painel.getByRole('button', { name: 'Agendar', exact: true })).toBeDisabled()
  await expect(painel.getByRole('checkbox', { name: /confirmo a marcação manual/ })).toHaveCount(0)
  await expect(painel.getByLabel(/^Início/)).toHaveValue('11:00')
})

test('consulta e espera usam fluxos distintos; chegada preserva edição na mesma data', async ({ page }) => {
  await abrir(page)
  await page.getByRole('button', { name: /^09:00 Bruno Exemplo/ }).click()
  const consulta = page.getByRole('dialog', { name: 'Consultar agendamento' })
  await expect(consulta).toContainText('Aguardando')
  await consulta.getByRole('button', { name: 'Editar agendamento' }).click()
  const edicao = page.getByRole('dialog', { name: 'Editar agendamento' })
  await expect(edicao.getByLabel('Nova data')).toBeDisabled()
  await expect(edicao).toContainText('Chegada preservada')
  await page.keyboard.press('Escape')
  await expect(edicao).toHaveCount(0)
  await page.getByRole('region', { name: 'Lista de espera' }).getByRole('button', { name: /^Encaixar/ }).click()
  const criacao = page.getByRole('dialog', { name: 'Novo agendamento' })
  await expect(pacienteEscolhido(criacao)).toContainText('Davi Exemplo Sintético')
  await expect(radioProfissional(criacao, 'prof-2')).toBeChecked()
  await criacao.getByRole('button', { name: 'Outro horário', exact: true }).click()
  await expect(criacao.getByLabel(/^Início/)).toHaveValue('')
  await expect(criacao.getByRole('button', { name: 'Agendar', exact: true })).toBeDisabled()
  await expect(page.getByTestId('registro-agenda')).toHaveCount(3)
})
