import { expect, test, type Page } from '@playwright/test'
test.setTimeout(90000)
const U='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',V='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'
async function navegarSecao(raiz: Page | import('@playwright/test').Locator, label: string) { const sel=raiz.getByRole('combobox',{name:'Seção',exact:true}); if(await sel.isVisible())await sel.selectOption({label}); else await raiz.getByRole('navigation',{name:'Seções da ficha'}).getByRole('button',{name:label,exact:true}).click(); }
async function abrir(page:Page, escuro=false) {
  await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort())
  await page.goto('/tests/operacional/equipe-fichas-demo.html')
  await expect(page.getByRole('button',{name:'Ver cadastro de Médico CLT Sintético',exact:true})).toBeVisible({timeout:60000})
  if (escuro) await page.getByRole('button',{name:'Ativar modo escuro'}).click()
  await page.getByRole('button',{name:'Ver cadastro de Médico CLT Sintético',exact:true}).click()
  await navegarSecao(page,'Atuação e atendimentos')
  const s=page.locator('[data-ficha-secao="atuacao"]')
  await expect(s.getByText('30 min · configuração do profissional, compartilhada entre suas clínicas.')).toBeVisible()
  return s
}
async function controle(page:Page,falha:string) { await page.evaluate(falha=>window.dispatchEvent(new CustomEvent('controle-demo-atuacao',{detail:{falha}})),falha) }
test('fontes por unidade, ausência, contexto e responsividade',async({page},info)=>{
  const s=await abrir(page)
  await expect(s).toContainText('R$ 180,00')
  await expect(s).toContainText('20% · regra da clínica')
  await expect(s.getByRole('button',{name:'Configurar serviços — indisponível'})).toBeDisabled()
  await s.getByRole('combobox',{name:'Clínica da atuação'}).selectOption(V)
  await expect(s).toContainText('R$ 240,00')
  await expect(s).toContainText('25% · regra da clínica')
  await expect(s).toContainText('Sem horário habitual cadastrado')
  await s.getByText('Catálogo existente desta clínica (0)',{exact:true}).click()
  await expect(s.getByText('Nenhum serviço ativo nesta clínica.')).toBeVisible()
  await expect(page.getByRole('combobox',{name:'Selecionar clínica',exact:true})).toHaveValue(U)
  await expect(page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).resolves.toBe(true)
  await page.screenshot({path:`scratch/equipe-atuacao/${info.project.name}.png`})
  await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click()
  await page.getByLabel('Buscar por nome, cargo ou profissão').fill('Médico CLT')
  await page.getByRole('button',{name:'Ver cadastro de Médico CLT Sintético',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click()
  await expect(page.getByLabel('Buscar por nome, cargo ou profissão')).toHaveValue('Médico CLT')
})
test('preço persiste sinteticamente por clínica e duração é compartilhada',async({page})=>{
  let s=await abrir(page)
  await s.getByRole('button',{name:'Editar preço nesta clínica',exact:true}).click()
  await s.getByLabel('Preço nesta clínica (R$)').fill('199,90')
  await s.getByRole('button',{name:'Salvar configuração'}).click()
  await expect(s).toContainText('R$ 199,90')
  await s.getByRole('combobox',{name:'Clínica da atuação'}).selectOption(V)
  await expect(s).toContainText('R$ 240,00')
  await s.getByRole('button',{name:'Editar duração da Agenda'}).click()
  await s.getByLabel('Duração compartilhada (minutos)').fill('40')
  await s.getByRole('button',{name:'Salvar configuração'}).click()
  await expect(s).toContainText('40 min · configuração do profissional')
  await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click()
  await page.reload()
  await page.getByRole('button',{name:'Ver cadastro de Médico CLT Sintético',exact:true}).click()
  await navegarSecao(page,'Atuação e atendimentos')
  s=page.locator('[data-ficha-secao="atuacao"]')
  await expect(s).toContainText('R$ 199,90')
  await expect(s).toContainText('40 min · configuração do profissional')
})
test('falha de escrita preserva rascunho, conflito bloqueia repetição e descarte é explícito',async({page})=>{
  const s=await abrir(page)
  await s.getByRole('button',{name:'Editar preço nesta clínica'}).click()
  await s.getByLabel('Preço nesta clínica (R$)').fill('215')
  await controle(page,'PT409')
  await s.getByRole('button',{name:'Salvar configuração'}).click()
  await expect(s).toContainText('mudou em outra sessão')
  await expect(s.getByLabel('Preço nesta clínica (R$)')).toHaveValue('215')
  await expect(s.getByRole('button',{name:'Salvar configuração'})).toBeDisabled()
  await expect(s.getByRole('combobox',{name:'Clínica da atuação'})).toBeDisabled()
  await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click()
  await expect(page.getByRole('alertdialog')).toContainText('Descartar alterações desta ficha?')
  await page.getByRole('alertdialog').getByRole('button',{name:'Cancelar',exact:true}).click()
  await controle(page,'')
  await s.getByRole('button',{name:'Reconsultar atuação'}).click()
  await page.getByRole('button',{name:'Descartar e reconsultar',exact:true}).click()
  await expect(s).toContainText('R$ 180,00')
})
test('consulta negada não vira ausência e horários usam o editor existente',async({page})=>{
  const s=await abrir(page)
  await controle(page,'42501')
  await s.getByRole('button',{name:'Reconsultar atuação'}).click()
  await expect(s).toContainText('Você não tem autorização')
  await expect(s.getByRole('button',{name:'Editar preço nesta clínica'})).toHaveCount(0)
  await controle(page,'')
  await s.getByRole('button',{name:'Reconsultar atuação'}).click()
  await s.getByRole('button',{name:'Abrir configuração de horários'}).click()
  await expect(s.getByRole('button',{name:'Salvar horários'})).toBeVisible()
  await expect(page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).resolves.toBe(true)
  await s.getByRole('button',{name:'+ Adicionar linha',exact:true}).click()
  await s.getByRole('button',{name:'Cancelar',exact:true}).click()
  await expect(page.getByRole('alertdialog')).toContainText('Descartar horários não salvos?')
  await page.getByRole('button',{name:'Descartar horários',exact:true}).click()
  await s.getByRole('button',{name:'Fechar configuração de horários'}).click()
  await expect(s).toContainText('Segunda · 08:00–12:00')
})
test('modo escuro e backend ausente mantêm estados claros; logout ignora resposta atrasada',async({page})=>{
  const s=await abrir(page,true)
  await controle(page,'PGRST202')
  await s.getByRole('button',{name:'Reconsultar atuação'}).click()
  await expect(s).toContainText('Atuação indisponível neste ambiente')
  await expect(s.getByRole('button',{name:'Editar duração da Agenda'})).toHaveCount(0)
  await controle(page,'')
  await s.getByRole('button',{name:'Reconsultar atuação'}).click()
  await expect(s).toContainText('R$ 180,00')
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('controle-demo-atuacao',{detail:{atraso:true}})))
  await s.getByRole('button',{name:'Reconsultar atuação'}).click()
  await page.evaluate(async()=>{const {supabase}=await import('/src/lib/supabase.ts');await supabase.auth.signOut({scope:'local'})})
  await page.evaluate(()=>window.dispatchEvent(new Event('liberar-demo-atuacao')))
  await expect(page.locator('[data-ficha-secao="atuacao"]')).toHaveCount(0)
  await expect(page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true})).toBeEnabled()
})
