import {test,expect,type Page,type Locator} from '@playwright/test';
import {abrirSecaoFicha} from './equipe-ficha-helpers';
test.setTimeout(60000);
async function preparar(page:Page){await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.goto('/tests/operacional/equipe-fichas-demo.html');await expect(page.getByRole('button',{name:'Ver cadastro de Médica Sintética',exact:true})).toBeVisible({timeout:30000});}
async function abrir(page:Page,nome='Médico CLT Sintético'){await page.getByRole('button',{name:'Ver cadastro de '+nome,exact:true}).click();const d=page.getByRole('dialog').filter({has:page.getByRole('heading',{name:nome,exact:true})});await expect(d.getByRole('heading',{name:'Visão geral',exact:true})).toBeVisible();await expect(d.getByRole('button',{name:'Atualizar informações da ficha'})).toBeEnabled();return d;}
async function secao(d:Locator,label:string){await abrirSecaoFicha(d,label);}
async function controle(page:Page,data:Record<string,unknown>){await page.evaluate(d=>window.dispatchEvent(new CustomEvent('controle-demo-ficha',{detail:d})),data);}
test('photo and recebimento drafts remain mounted across sections and discard stays explicit',async({page})=>{
 await preparar(page);const d=await abrir(page);await d.getByRole('button',{name:'Gerenciar foto',exact:true}).click();
 const foto=d.getByLabel('Adicionar foto',{exact:true});await foto.setInputFiles('scratch/equipe-fotos-recebimento/foto-sintetica.jpg');await expect(d.getByAltText('Prévia da foto selecionada')).toBeVisible();
 await secao(d,'Documentos');await secao(d,'Visão geral');await expect(foto).toHaveValue(/foto-sintetica.jpg$/);await d.getByRole('button',{name:'Cancelar foto',exact:true}).click();
 await secao(d,'Recebimento');await d.getByRole('button',{name:'Cadastrar dados de recebimento'}).click();await d.getByRole('checkbox',{name:'Cadastrar PIX',exact:true}).check();await d.getByLabel('Chave PIX',{exact:true}).fill('somente-ficticio@example.invalid');
 await secao(d,'Formação e registros');await expect(d.getByRole('button',{name:'Editar formação e registros',exact:true})).toBeVisible();await secao(d,'Recebimento');await expect(d.getByLabel('Chave PIX',{exact:true})).toHaveValue('somente-ficticio@example.invalid');
 await d.getByRole('button',{name:'Fechar',exact:true}).click();await expect(page.getByRole('alertdialog')).toBeVisible();await page.getByRole('button',{name:'Descartar e fechar',exact:true}).click();
});
test('initial registration keeps CPF optional, validates fields and offers the confirmed new ficha',async({page})=>{
 await preparar(page);await page.getByRole('button',{name:'Novo membro',exact:true}).click();
 const f=page.getByRole('dialog',{name:'Novo membro da equipe',exact:true});
 await f.getByLabel('Tipo de função *').selectOption('administrativo');await f.getByLabel('Cargo ou função *').selectOption('Recepcionista');
 await f.getByRole('button',{name:'Salvar cadastro',exact:true}).click();await expect(f.getByLabel('Nome completo *')).toBeFocused();
 await expect(f.getByLabel('CPF (opcional)')).toBeVisible();
 const nome='Pessoa inteiramente fictícia de nome longo para revisão da ficha visual trinta e seis';
 await f.getByLabel('Nome completo *').fill(nome);await f.getByRole('button',{name:'Salvar cadastro',exact:true}).click();
 await expect(f).toHaveCount(0);await page.getByRole('button',{name:'Continuar na ficha criada',exact:true}).click();
 const d=page.getByRole('dialog').filter({has:page.getByRole('heading',{name:new RegExp('^'+nome+'$','i')})});
 await expect(d.getByRole('heading',{name:'Visão geral',exact:true})).toBeVisible();await secao(d,'Dados pessoais');
 await expect(d.getByText('Não informado', {exact:true}).first()).toBeVisible();await expect(d.getByRole('button',{name:'Editar cadastro básico',exact:true})).toBeVisible();
 await page.screenshot({path:'scratch/equipe-36/nome-longo.png'});
});
test('access confirmed roles and explicit grant choices survive navigation and protect discard',async({page})=>{
 await preparar(page);await controle(page,{conta:true});let d=await abrir(page);await secao(d,'Acesso ao sistema');
 const papel=d.getByRole('combobox',{name:'Papel de Clínica Brotas',exact:true});
 await expect(papel).toHaveValue('recepcao');const salvar=d.getByRole('button',{name:'Salvar papel',exact:true}).first();await expect(salvar).toBeDisabled();
 await papel.selectOption('medico');await expect(salvar).toBeEnabled();await secao(d,'Visão geral');await secao(d,'Acesso ao sistema');await expect(papel).toHaveValue('medico');
 await d.getByRole('button',{name:'Fechar',exact:true}).click();await expect(page.getByRole('alertdialog')).toBeVisible();await page.getByRole('button',{name:'Descartar e fechar',exact:true}).click();
 await controle(page,{conta:true,papelConfirmado:null});d=await abrir(page);await secao(d,'Acesso ao sistema');await expect(d.getByRole('combobox',{name:'Papel de Clínica Brotas',exact:true})).toBeDisabled();await expect(d.getByRole('button',{name:'Salvar papel',exact:true}).first()).toBeDisabled();await d.getByRole('button',{name:'Fechar',exact:true}).click();
 await controle(page,{});d=await abrir(page);await secao(d,'Acesso ao sistema');await expect(d.getByRole('button',{name:'Enviar convite',exact:true})).toBeDisabled();await expect(d.getByRole('combobox',{name:'Papel para Clínica Brotas',exact:true})).toHaveValue('');
 await d.getByRole('combobox',{name:'Papel para Clínica Brotas',exact:true}).selectOption('recepcao');await secao(d,'Documentos');await secao(d,'Acesso ao sistema');await expect(d.getByRole('combobox',{name:'Papel para Clínica Brotas',exact:true})).toHaveValue('recepcao');
 await d.getByRole('button',{name:'Fechar',exact:true}).click();await expect(page.getByRole('alertdialog')).toBeVisible();await page.getByRole('button',{name:'Descartar e fechar',exact:true}).click();
});
test('workspace keeps one visible section, profile applicability, header and focus return',async({page})=>{await preparar(page);for(const nome of ['Recepção Sintética','Médica Sintética','Médico CLT Sintético']){const opener=page.getByRole('button',{name:'Ver cadastro de '+nome,exact:true});const d=await abrir(page,nome);await expect(d.locator('[data-ficha-secao]:visible')).toHaveCount(1);await expect(d.locator('.equipe-ficha-retrato .equipe-avatar')).toBeVisible();await secao(d,'Contratos e jornada');await expect(d.locator('.equipe-ficha-contrato')).toHaveCount(1);if(nome==='Recepção Sintética')await expect(d.locator('[data-ficha-secao="atuacao"]')).toHaveCount(0);else{await secao(d,'Atuação e atendimentos');await expect(d.getByRole('button',{name:'Abrir configuração de horários',exact:true})).toBeVisible();}for(const label of ['Dados pessoais','Documentos','Acesso ao sistema','Histórico','Visão geral']){await secao(d,label);await expect(d.locator('[data-ficha-secao]:visible')).toHaveCount(1);}await d.getByRole('button',{name:'Fechar',exact:true}).click();await expect(opener).toBeFocused();}});
test('draft survives section navigation, failure, explicit discard, reopen and synthetic F5',async({page})=>{await preparar(page);let d=await abrir(page,'Recepção Sintética');await secao(d,'Dados pessoais');await d.getByRole('button',{name:/^(Completar|Editar) dados complementares$/}).click();const f=d.getByRole('form',{name:'Salvar dados pessoais'});await f.getByLabel('Nome social (quando informado)').fill('Rascunho fictício 36');await secao(d,'Documentos');await secao(d,'Dados pessoais');await expect(f.getByLabel('Nome social (quando informado)')).toHaveValue('Rascunho fictício 36');await controle(page,{falha:'CONFLITO'});await f.getByRole('button',{name:'Salvar dados pessoais',exact:true}).click();await expect(f.getByLabel('Nome social (quando informado)')).toHaveValue('Rascunho fictício 36');await expect(f.getByRole('button',{name:'Salvar dados pessoais',exact:true})).toBeDisabled();await d.getByRole('button',{name:'Fechar',exact:true}).click();await expect(page.getByRole('alertdialog')).toContainText('Descartar');await page.getByRole('button',{name:'Descartar e fechar',exact:true}).click();await controle(page,{});d=await abrir(page,'Recepção Sintética');await secao(d,'Dados pessoais');await d.getByRole('button',{name:/^(Completar|Editar) dados complementares$/}).click();await d.getByLabel('Nome social (quando informado)').fill('Nome social fictício confirmado');await d.getByRole('button',{name:'Salvar dados pessoais',exact:true}).click();await expect(d.getByTestId('ficha-secao-complementares').getByText('Nome social fictício confirmado',{exact:true})).toBeVisible();await d.getByRole('button',{name:'Fechar',exact:true}).click();await page.reload();d=await abrir(page,'Recepção Sintética');await secao(d,'Dados pessoais');await expect(d.getByTestId('ficha-secao-complementares').getByText('Nome social fictício confirmado',{exact:true})).toBeVisible();});
test('documents retain selected file, exact versions, review, download and archive',async({page})=>{await preparar(page);const d=await abrir(page);await secao(d,'Documentos');await d.getByRole('button',{name:'Adicionar documento',exact:true}).click();const f=d.getByRole('form',{name:'Adicionar documento privado'});await f.getByRole('combobox',{name:'Categoria',exact:true}).selectOption('contrato');await f.getByLabel('Arquivo PDF, JPEG ou PNG').setInputFiles('scratch/equipe-fichas-completas/documento-ficticio.pdf');await secao(d,'Visão geral');await secao(d,'Documentos');await expect(f.getByText(/Arquivo selecionado:.*documento-ficticio.pdf/)).toBeVisible();await f.getByRole('button',{name:'Salvar documento',exact:true}).click();await expect(f.getByText(/Documento salvo: arquivo e registro confirmados/)).toBeVisible();const atual=d.locator('.equipe-documentos-lista article');await expect(atual).toHaveCount(1);await atual.getByRole('button',{name:/^Mais ações para /}).click();await d.getByRole('menuitem',{name:'Substituir versão 1',exact:true}).click();await f.getByLabel('Arquivo PDF, JPEG ou PNG').setInputFiles('scratch/equipe-fichas-completas/documento-ficticio.pdf');await f.getByRole('button',{name:'Salvar documento',exact:true}).click();await expect(atual).toContainText('versão 2');await expect(d.locator('.equipe-documentos-anteriores')).toContainText('versão 1');await atual.getByRole('button',{name:/^Mais ações para /}).click();await d.getByRole('menuitem',{name:'Conferir versão 2',exact:true}).click();const conf=d.getByRole('form',{name:'Conferir documento salvo'});await conf.getByLabel('Fonte / critério da conferência').fill('Conferência sintética 36');await conf.getByRole('button',{name:'Salvar conferência do documento'}).click();await expect(atual).toContainText('Conferido');const download=page.waitForEvent('download');await atual.getByRole('button',{name:'Baixar versão 2',exact:true}).click();expect((await download).suggestedFilename()).toContain('2');await atual.getByRole('button',{name:'Visualizar versão 2',exact:true}).click();await expect(d.getByRole('button',{name:'Fechar visualização'})).toBeVisible();await d.getByRole('button',{name:'Fechar visualização'}).click();await atual.getByRole('button',{name:/^Mais ações para /}).click();await d.getByRole('menuitem',{name:'Arquivar versão 2',exact:true}).click();await page.getByRole('button',{name:'Arquivar documento',exact:true}).click();await expect(atual).toHaveCount(0);await d.locator('.equipe-documentos-anteriores > [data-slot=collapsible-trigger]').click();await expect(d.locator('.equipe-documentos-anteriores article:visible')).toHaveCount(2);});
test('keyboard navigation, dark mode and member/clinic changes preserve context',async({page})=>{await preparar(page);await page.getByRole('button',{name:'Ativar modo escuro'}).click();const d=await abrir(page);await secao(d,'Dados pessoais');await expect(d.locator('[data-ficha-secao="pessoal"]>h3')).toBeFocused();await page.keyboard.press('Tab');expect(await d.evaluate(el=>el.contains(document.activeElement))).toBe(true);await d.getByRole('button',{name:'Fechar',exact:true}).click();await page.getByRole('combobox',{name:'Selecionar clínica',exact:true}).selectOption('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb');const outro=await abrir(page,'Recepção Sintética');await expect(outro.getByRole('heading',{name:'Recepção Sintética',exact:true})).toBeVisible();await expect(outro.getByRole('heading',{name:'Médico CLT Sintético',exact:true})).toHaveCount(0);await expect(outro.locator('.equipe-ficha-vinculos')).toContainText('Clínica Ipupiara');await outro.getByRole('button',{name:'Fechar',exact:true}).click();});
for(const width of [360,390,430,820,1440])test(`workspace ${width}px: single content scroll and usable fixed navigation`,async({page})=>{await page.setViewportSize({width,height:900});await preparar(page);const d=await abrir(page);const nav=d.getByRole('navigation',{name:'Seções da ficha'});await expect(nav).toBeVisible();const primeiro=await nav.getByRole('button').first().boundingBox(),ultimo=await nav.getByRole('button').last().boundingBox();expect(width<900?primeiro!.y===ultimo!.y:primeiro!.y<ultimo!.y).toBe(true);await secao(d,'Dados pessoais');await d.getByRole('button',{name:/^(Completar|Editar) dados complementares$/}).click();await d.getByLabel('Nome social (quando informado)').fill('Nome fictício comprido para verificar largura e conteúdo');await expect(d.getByRole('button',{name:'Salvar dados pessoais',exact:true})).toBeVisible();const dimensoes=await d.evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth,doc:document.documentElement.scrollWidth,viewport:innerWidth,scrolls:[...el.querySelectorAll<HTMLElement>('*')].filter(e=>e.clientHeight>0&&e.scrollHeight>e.clientHeight+2&&getComputedStyle(e).overflowY==='auto').map(e=>e.className)}));expect(dimensoes.scroll).toBeLessThanOrEqual(dimensoes.client+1);expect(dimensoes.doc).toBeLessThanOrEqual(dimensoes.viewport);if(width<640){/* Abaixo de 640px o cabeçalho rola com o conteúdo: a única rolagem é o próprio diálogo e o menu fica fixo no topo. */expect(dimensoes.scrolls).toEqual([]);const rolagem=await d.evaluate(el=>{const antes=el.scrollTop;el.scrollTop=0;const topo=el.scrollTop;el.scrollTop=400;const menu=el.querySelector('.equipe-ficha-lateral')!.getBoundingClientRect().top-el.getBoundingClientRect().top;const r={estilo:getComputedStyle(el).overflowY,rolou:el.scrollTop>topo,menu};el.scrollTop=antes;return r});expect(rolagem.estilo).toBe('auto');expect(rolagem.rolou).toBe(true);expect(Math.abs(rolagem.menu)).toBeLessThanOrEqual(2)}else expect(dimensoes.scrolls).toEqual(['equipe-ficha-conteudo']);await secao(d,'Visão geral');await page.screenshot({path:`scratch/equipe-36/depois-${width}.png`});await d.getByRole('button',{name:'Fechar',exact:true}).click();await page.getByRole('button',{name:'Descartar e fechar',exact:true}).click();});
