import { expect, test, type Page } from '@playwright/test';
test.setTimeout(90000);
const PDF = 'scratch/equipe-fichas-completas/documento-ficticio.pdf';
const U = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', V = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
async function navegarSecao(raiz: Page | import('@playwright/test').Locator, label: string) { const sel=raiz.getByRole('combobox',{name:'Seção',exact:true}); if(await sel.isVisible())await sel.selectOption({label}); else await raiz.getByRole('navigation',{name:'Seções da ficha'}).getByRole('button',{name:label,exact:true}).click(); }
async function abrirEnvio(raiz: Page | import('@playwright/test').Locator){await navegarSecao(raiz,'Documentos');const b=raiz.getByRole('button',{name:'Adicionar documento',exact:true});if(await b.isVisible())await b.click();}
async function acaoDocumento(raiz: import('@playwright/test').Locator,label:string){const b=raiz.getByRole('button',{name:label,exact:true});if(!await b.isVisible())await raiz.locator('.equipe-documentos-lista article details>summary').click();await b.click();}
async function preparar(page: Page) { page.on('pageerror', e => console.error('Erro de execução na demonstração sintética:', e.message)); await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort()); await page.goto('/tests/operacional/equipe-fichas-demo.html'); await expect(page.getByRole('button', { name: 'Ver cadastro de Médica Sintética', exact: true })).toBeVisible({ timeout: 30000 }); }
async function abrir(page: Page, nome = 'Médico CLT Sintético') { await page.getByRole('button', { name: 'Ver cadastro de ' + nome, exact: true }).click(); await navegarSecao(page,'Dados pessoais'); await expect(page.getByRole('button', { name: 'Editar dados pessoais', exact: true })).toBeVisible(); return page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Ficha de ' + nome, exact: true }) }); }
async function controle(page: Page, d: Record<string, unknown>) { await page.evaluate(d => window.dispatchEvent(new CustomEvent('controle-demo-ficha', { detail: d })), d); }
async function documento(page: Page) { await abrirEnvio(page); const f = page.getByRole('form', { name: 'Adicionar documento privado' }); await f.getByRole('combobox', { name: 'Categoria', exact: true }).selectOption('contrato'); await f.getByLabel('Arquivo PDF, JPEG ou PNG').setInputFiles(PDF); await f.getByRole('button', { name: 'Salvar documento', exact: true }).click(); await expect(f.getByText(/Documento salvo: arquivo e registro confirmados/)).toBeVisible(); return f; }
test('document metadata alone is a draft; cancel requires discard and dark-mode controls remain usable', async ({ page }) => {
    await preparar(page);
    await page.getByRole('button', { name: 'Ativar modo escuro' }).click();
    const d = await abrir(page);
    await abrirEnvio(d); const f = d.getByRole('form', { name: 'Adicionar documento privado' });
    await f.getByRole('combobox', { name: 'Categoria', exact: true }).selectOption('contrato');
    await f.getByRole('button', { name: 'Cancelar documento', exact: true }).click();
    await expect(page.getByRole('alertdialog')).toContainText('Descartar seleção de documento?');
    await page.getByRole('button', { name: 'Descartar seleção', exact: true }).click();
    await abrirEnvio(d); await expect(f.getByRole('combobox', { name: 'Categoria', exact: true })).toHaveValue('');
    await navegarSecao(d,'Documentos');
    await expect(f.getByRole('button', { name: 'Salvar documento', exact: true })).toBeDisabled();
});
test('occupational controls require specific synthetic capability and never collect clinical content', async ({ page }) => {
    await preparar(page);
    await controle(page, { ocupacional: true });
    const d = await abrir(page);
    await navegarSecao(d,'Contratos e jornada'); await d.getByText('Acompanhamento ocupacional administrativo autorizado', { exact: true }).click();
    await d.getByRole('button', { name: 'Adicionar acompanhamento ocupacional', exact: true }).click();
    const f = d.getByRole('form', { name: 'Salvar acompanhamento ocupacional' });
    await expect(f.getByLabel('Data administrativa do ASO')).toBeVisible();
    await expect(f.getByLabel(/Diagnóstico|Resultado clínico|Prontuário/)).toHaveCount(0);
    await abrirEnvio(d); await expect(d.getByRole('combobox', { name: 'Categoria', exact: true }).locator('option[value="aso"]')).toHaveCount(1);
    await f.getByRole('button', { name: 'Cancelar acompanhamento ocupacional', exact: true }).click();
    await d.getByRole('button', { name: 'Fechar', exact: true }).click();
    await controle(page, {});
    const sem = await abrir(page);
    await expect(sem.getByText('Acompanhamento ocupacional administrativo autorizado', { exact: true })).toHaveCount(0);
});
test('additional single-unit contract does not duplicate the person or copy into the other clinic', async ({ page }) => {
    await preparar(page);
    await page.getByRole('combobox', { name: 'Selecionar clínica', exact: true }).selectOption(V);
    let d = await abrir(page);
    await navegarSecao(d,'Contratos e jornada'); await d.getByRole('button', { name: 'Adicionar contrato', exact: true }).click();
    const f = d.getByRole('form', { name: 'Salvar contrato' });
    await f.getByRole('combobox', { name: 'Empresa contratante', exact: true }).selectOption('44444444-4444-4444-8444-444444444444');
    await f.getByLabel('Admissão / início do contrato').fill('2026-10-01');
    await f.getByLabel('Vigência desta versão').fill('2026-10-01');
    await f.getByLabel('Cargo contratual', { exact: true }).fill('Cargo adicional fictício de Ipupiara');
    await f.getByRole('button', { name: 'Salvar contrato', exact: true }).click();
    await expect(d.locator('.equipe-ficha-contrato')).toHaveCount(2);
    await d.getByRole('button', { name: 'Fechar', exact: true }).click();
    await page.getByRole('combobox', { name: 'Selecionar clínica', exact: true }).selectOption(U);
    d = await abrir(page);
    await expect(d.locator('.equipe-ficha-contrato')).toHaveCount(1);
    await expect(d.getByText('Cargo adicional fictício de Ipupiara', { exact: true })).toHaveCount(0);
    await d.getByRole('button', { name: 'Fechar', exact: true }).click();
    await expect(page.getByRole('status').filter({ hasText: '3 pessoas no resultado' })).toBeVisible();
});
test('CLT staff, contractor doctor and CLT doctor keep identity, contract and professional records separate', async ({ page }) => {
    await preparar(page);
    for (const nome of ['Recepção Sintética', 'Médica Sintética', 'Médico CLT Sintético']) {
        const d = await abrir(page, nome);
        await expect(d.locator('.equipe-ficha-contrato')).toHaveCount(1);
        await expect(d.locator('.equipe-ficha-contrato')).toContainText('Clínica Brotas · Clínica Ipupiara');
        if (nome === 'Recepção Sintética') {
            await expect(d.getByRole('button', { name: 'Formação e registros', exact: true })).toHaveCount(0);
            await expect(d.getByRole('button', { name: 'Recebimento', exact: true })).toHaveCount(0);
        }
        else
            await expect(d.locator('[data-ficha-secao="formacao"]')).toHaveCount(1);
        await d.getByRole('button', { name: 'Fechar', exact: true }).click();
    }
    await expect(page.getByRole('status').filter({ hasText: '3 pessoas no resultado' })).toBeVisible();
});
test('personal data persists in explicitly synthetic store through reopen/F5; purpose conditions and discard work', async ({ page }) => { await preparar(page); let d = await abrir(page, 'Recepção Sintética'); await d.getByRole('button', { name: 'Editar dados pessoais', exact: true }).click(); const f = d.getByRole('form', { name: 'Salvar dados pessoais' }); await f.getByLabel('Nome social (quando informado)').fill('Nome Social Fictício'); await expect(f.getByLabel('Nacionalidade para admissão')).toHaveCount(0); await f.getByLabel('Há finalidade de admissão').check(); await f.getByLabel('Nacionalidade para admissão').fill('Declarada Sintética'); await f.getByRole('button', { name: 'Salvar dados pessoais', exact: true }).click(); await expect(d.getByText('Nome Social Fictício · Não informado')).toBeVisible(); await d.getByRole('button', { name: 'Fechar', exact: true }).click(); await page.reload(); d = await abrir(page, 'Recepção Sintética'); await expect(d.getByText('Nome Social Fictício · Não informado')).toBeVisible(); await d.getByRole('button', { name: 'Editar dados pessoais', exact: true }).click(); await d.getByLabel('Nome social (quando informado)').fill('Rascunho Fictício'); await d.getByRole('button', { name: 'Fechar', exact: true }).click(); await expect(page.getByRole('alertdialog')).toContainText('Descartar'); await page.getByRole('button', { name: 'Descartar e fechar' }).click(); d = await abrir(page, 'Recepção Sintética'); await expect(d.getByText('Nome Social Fictício · Não informado')).toBeVisible(); });
test('load refusal is not absence and cannot save blank sections; specific scope excludes shared records', async ({ page }) => { await preparar(page); await controle(page, { papel: 'recepcao' }); await page.getByRole('button', { name: 'Ver cadastro de Médica Sintética', exact: true }).click(); await expect(page.getByText('Informações adicionais indisponíveis')).toBeVisible(); await expect(page.getByRole('button', { name: 'Editar dados pessoais', exact: true })).toHaveCount(0); await page.getByRole('dialog').getByRole('button', { name: 'Fechar', exact: true }).click(); await controle(page, { permitidas: [U] }); await page.getByRole('button', { name: 'Ver cadastro de Médica Sintética', exact: true }).click(); await navegarSecao(page,'Dados pessoais'); await expect(page.getByText('Dados canônicos restritos:').first()).toBeVisible(); await expect(page.locator('.equipe-ficha-contrato')).toHaveCount(0); await expect(page.getByText('Acompanhamento ocupacional administrativo autorizado')).toHaveCount(0); });
test('contract versions preserve salary/schedule snapshots without duplicating person or granting access', async ({ page }) => { await preparar(page); let d = await abrir(page); await navegarSecao(d,'Contratos e jornada'); await d.getByRole('button', { name: 'Editar contrato', exact: true }).click(); const f = d.getByRole('form', { name: 'Salvar contrato' }); await f.getByLabel('Cargo contratual', { exact: true }).fill('Cargo Fictício Revisto'); await f.getByLabel('Vigência desta versão').fill('2026-10-05'); await f.getByLabel('Remuneração contratual (restrita)').fill('100.50'); await f.getByRole('button', { name: 'Adicionar jornada por unidade' }).click(); await f.getByLabel('Unidade da jornada').selectOption(U); await f.getByLabel('Entrada', { exact: true }).fill('08:00'); await f.getByLabel('Saída', { exact: true }).fill('12:00'); await f.getByRole('button', { name: 'Salvar contrato', exact: true }).click(); await expect(d.locator('.equipe-ficha-contrato')).toContainText('versão 2'); await expect(d.locator('.equipe-ficha-contrato')).toHaveCount(1); await navegarSecao(d,'Contratos e jornada'); await d.getByRole('button', { name: 'Editar contrato', exact: true }).click(); await d.getByRole('form', { name: 'Salvar contrato' }).getByLabel('Cargo contratual', { exact: true }).fill('Cargo Fictício Atual'); await d.getByRole('form', { name: 'Salvar contrato' }).getByRole('button', { name: 'Salvar contrato', exact: true }).click(); await expect(d.locator('.equipe-ficha-contrato')).toContainText('versão 3'); await navegarSecao(d,'Histórico'); await d.getByRole('button', { name: 'Consultar versão 2', exact: true }).click(); await expect(d.getByText('Versão 2 · somente leitura')).toBeVisible(); await expect(d.getByText('Cargo Fictício Revisto · clt', { exact: true })).toBeVisible(); await d.getByRole('button', { name: 'Fechar', exact: true }).click(); d = await abrir(page); await expect(d.locator('.equipe-ficha-contrato')).toContainText('Cargo Fictício Atual'); await navegarSecao(d,'Acesso ao sistema'); await expect(d.getByText('Sem conta vinculada', { exact: true })).toBeVisible(); });
test('multiple councils/specialties, explicit professional verification and changed registration reset', async ({ page }) => { await preparar(page); let d = await abrir(page); await navegarSecao(d,'Formação e registros'); await d.getByRole('button', { name: 'Editar formação e registros', exact: true }).click(); const f = d.getByRole('form', { name: 'Salvar formação e registros' }); await f.getByRole('button', { name: 'Adicionar inscrições em conselhos' }).click(); await f.getByLabel('Conselho (CRM, COREN, CRP…)').fill('CRM'); await f.getByLabel('Número da inscrição').fill('12345'); await f.getByLabel('UF da inscrição').selectOption('BA'); await f.getByRole('button', { name: 'Adicionar especialidades e áreas de atuação' }).click(); await f.getByLabel('Especialidade informada').fill('Especialidade Sintética'); const regValue = await f.getByLabel('Inscrição correspondente').locator('option').nth(1).getAttribute('value'); await f.getByLabel('Inscrição correspondente').selectOption(regValue!); await f.getByLabel('RQE (somente médico com CRM correspondente)').fill('101'); await f.getByRole('button', { name: 'Salvar formação e registros', exact: true }).click(); await navegarSecao(d,'Visão geral'); await expect(d.getByText("Inscrição CRM/BA: ainda não conferida.", {exact:true})).toBeVisible(); await navegarSecao(d,'Formação e registros'); await d.getByText('Conferir inscrição profissional salva', { exact: true }).click(); const cf = d.getByRole('form', { name: 'Conferência profissional' }); await cf.getByLabel('Inscrição', { exact: true }).selectOption(regValue!); await cf.getByLabel('Fonte consultada').fill('Fonte Sintética, sem consulta real'); await cf.getByRole('button', { name: 'Registrar conferência da inscrição' }).click(); await expect(d.getByText(/conferência: conferido/)).toBeVisible(); await navegarSecao(d,'Formação e registros'); await d.getByRole('button', { name: 'Editar formação e registros', exact: true }).click(); await d.getByLabel('Número da inscrição').fill('12346'); await d.getByRole('form', { name: 'Salvar formação e registros' }).getByRole('button', { name: 'Salvar formação e registros', exact: true }).click(); await expect(d.getByText(/conferência: aguardando/)).toBeVisible(); });
test('private document upload/reopen/F5/download/review/replacement preserve versions with fresh review', async ({ page }) => { await preparar(page); let d = await abrir(page); await documento(page); await acaoDocumento(d,'Conferir versão 1'); const cf = d.getByRole('form', { name: 'Conferir documento salvo' }); await cf.getByLabel('Fonte / critério da conferência').fill('Documento Fictício Conferido'); await cf.getByRole('button', { name: 'Salvar conferência do documento' }).click(); await expect(d.locator('article:visible')).toContainText('Conferência: conferido'); const download = page.waitForEvent('download'); await d.getByRole('button', { name: 'Baixar versão 1' }).click(); expect((await download).suggestedFilename()).toContain('v1.pdf'); await acaoDocumento(d,'Substituir versão 1'); await d.getByLabel('Arquivo PDF, JPEG ou PNG').setInputFiles(PDF); await d.getByRole('button', { name: 'Salvar documento', exact: true }).click(); await expect(d.locator('article:visible')).toContainText('versão 2'); await expect(d.locator('article:visible')).toContainText('Conferência: aguardando'); await d.locator('.equipe-documentos-anteriores>summary').click(); await expect(d.locator('article:visible')).toHaveCount(2); await d.getByRole('button', { name: 'Fechar', exact: true }).click(); await page.reload(); d = await abrir(page); await navegarSecao(d,'Documentos'); await expect(d.locator('article:visible')).toContainText('versão 2'); await d.locator('.equipe-documentos-anteriores>summary').click(); await expect(d.locator('article:visible')).toHaveCount(2); });
test('partial upload never reports success; same attempt recovers after reopen without duplicate document', async ({ page }) => { await preparar(page); let d = await abrir(page); await controle(page, { falha: 'parcial' }); await abrirEnvio(d); const f = d.getByRole('form', { name: 'Adicionar documento privado' }); await f.getByRole('combobox', { name: 'Categoria', exact: true }).selectOption('contrato'); await f.getByLabel('Arquivo PDF, JPEG ou PNG').setInputFiles(PDF); await f.getByRole('button', { name: 'Salvar documento', exact: true }).click(); await expect(f.getByText('Documento não confirmado nesta tentativa.')).toBeVisible(); await expect(d.locator('article:visible')).toHaveCount(0); await d.getByRole('button', { name: 'Fechar', exact: true }).click(); await page.getByRole('button', { name: 'Descartar e fechar' }).click(); await controle(page, {}); d = await abrir(page); await navegarSecao(d,'Documentos'); await expect(d.getByRole('button', { name: 'Retomar tentativa pendente' })).toBeVisible(); await d.getByRole('button', { name: 'Retomar tentativa pendente' }).click(); await d.getByRole('button', { name: 'Consultar resultado da tentativa' }).click(); await expect(d.locator('article:visible')).toHaveCount(1); await expect(d.locator('article:visible')).toContainText('Armazenamento: disponível'); await expect(d.getByRole('button', { name: 'Consultar resultado da tentativa' })).toHaveCount(0); });
test('document scope isolates second clinic and direct reads; occupational category stays restricted', async ({ page }) => { await preparar(page); let d = await abrir(page); await documento(page); const docId = await page.evaluate(async () => { const m = await import('/tests/operacional/equipe-fichas-simulador.ts'); const r = await m.simularFicha(new Request('https://operacional.synthetic.invalid/functions/v1/equipe-fichas', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ membroId: m.MED_CLT, clinicaId: m.UNIDADE_A, acao: 'obter' }) })); return (await r.json()).documentos[0].id; }); const denied = await page.evaluate(async ({ id, V }) => { const m = await import('/tests/operacional/equipe-fichas-simulador.ts'); return (await m.simularFicha(new Request('https://operacional.synthetic.invalid/functions/v1/equipe-fichas', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ membroId: m.MED_CLT, clinicaId: V, acao: 'documento_ler', id }) }), { permitidas: [V] })).status; }, { id: docId, V }); expect(denied).toBe(403); await expect(d.getByRole('combobox', { name: 'Categoria', exact: true }).locator('option[value="aso"]')).toHaveCount(0); await d.getByRole('button', { name: 'Fechar', exact: true }).click(); await page.getByRole('combobox', { name: 'Selecionar clínica', exact: true }).selectOption(V); d = await abrir(page); await navegarSecao(d,'Documentos'); await expect(d.locator('article:visible')).toHaveCount(0); await expect(d.locator('.equipe-ficha-contrato')).toHaveCount(1); });
test('conflict preserves draft, blocks repeat and reconsultation requires explicit discard', async ({ page }) => { await preparar(page); const d = await abrir(page); await d.getByRole('button', { name: 'Editar dados pessoais', exact: true }).click(); const f = d.getByRole('form', { name: 'Salvar dados pessoais' }); await f.getByLabel('Nome social (quando informado)').fill('Rascunho Sintético Mantido'); await controle(page, { falha: 'CONFLITO' }); await f.getByRole('button', { name: 'Salvar dados pessoais', exact: true }).click(); await expect(f.getByLabel('Nome social (quando informado)')).toHaveValue('Rascunho Sintético Mantido'); await expect(f.getByRole('button', { name: 'Salvar dados pessoais', exact: true })).toBeDisabled(); await d.getByRole('button', { name: 'Reconsultar informações adicionais' }).click(); await expect(page.getByRole('alertdialog')).toBeVisible(); await controle(page, {}); await page.getByRole('button', { name: 'Descartar e reconsultar' }).click(); await expect(d.getByRole('button', { name: 'Editar dados pessoais', exact: true })).toBeVisible(); });
test('late response after logout cannot repopulate private fields or leave modal blocked', async ({ page }) => { await preparar(page); const d = await abrir(page); await d.getByRole('button', { name: 'Editar dados pessoais', exact: true }).click(); await d.getByLabel('Nome social (quando informado)').fill('Nome Sintético em Rascunho'); await controle(page, { adiar: true }); await d.getByRole('form', { name: 'Salvar dados pessoais' }).getByRole('button', { name: 'Salvar dados pessoais', exact: true }).click(); await expect(d.getByRole('button', { name: 'Fechar', exact: true })).toBeDisabled(); await page.evaluate(async () => { const { supabase } = await import('/src/lib/supabase.ts'); await supabase.auth.signOut({ scope: 'local' }); }); await page.evaluate(() => window.dispatchEvent(new Event('liberar-demo-ficha'))); await expect(d.getByLabel('Nome social (quando informado)')).toHaveCount(0); await expect(d.getByRole('button', { name: 'Fechar', exact: true })).toBeEnabled(); await d.getByRole('button', { name: 'Fechar', exact: true }).click(); });
for (const width of [360, 390, 430, 820, 1440])
    test(`ficha ${width}px: one scroll surface, accessible navigation and reachable document buttons`, async ({ page }) => { await page.setViewportSize({ width, height: 900 }); await preparar(page); const d = await abrir(page); const posicaoPagina = await page.evaluate(() => scrollY); await navegarSecao(d,'Documentos'); expect(await page.evaluate(() => scrollY)).toBe(posicaoPagina); expect(await page.evaluate(() => getComputedStyle(document.body).overflow)).toBe('hidden'); await abrirEnvio(d); const f = d.getByRole('form', { name: 'Adicionar documento privado' }); await expect(f.getByRole('button', { name: 'Salvar documento', exact: true })).toBeVisible(); const dimensoes = await d.evaluate(el => ({ client: el.clientWidth, scroll: el.scrollWidth, documento: document.documentElement.scrollWidth, viewport: innerWidth, inners: [...el.querySelectorAll<HTMLElement>('[data-ficha-secao]')].filter(e => e.scrollHeight > e.clientHeight + 2 && getComputedStyle(e).overflowY === 'auto').length })); expect(dimensoes.scroll).toBeLessThanOrEqual(dimensoes.client + 1); expect(dimensoes.documento).toBeLessThanOrEqual(dimensoes.viewport); expect(dimensoes.inners).toBe(0); await page.screenshot({ path: `scratch/equipe-fichas-completas/ficha-${width}.png` }); await d.getByRole('button', { name: 'Fechar', exact: true }).click(); await page.getByRole('button', { name: 'Serviços', exact: true }).click(); await page.getByRole('button', { name: 'Equipe & acessos', exact: true }).click(); await expect(page.getByRole('button', { name: 'Ver cadastro de Médica Sintética', exact: true })).toBeVisible(); });
