import { expect, test, type Page } from '@playwright/test'

const inicial = { id: 'edicao-sintetica', clinica_id: 'clinica-sintetica', nome_completo: 'Ana Demonstração', data_nascimento: null, sexo: 'nao_informado', telefone: '77900000010', email: 'teste@example.invalid', endereco: 'Rua Sintética,  10\nBloco A, referência literal', observacoes: 'Observação administrativa sintética', foto_path: null, ativo: true, created_at: '2026-01-01T12:00:00Z', updated_at: '2026-09-25T12:00:00Z' }
async function preparar(page: Page, erro?: string, comResponsavel = true, foto = false) {
  let paciente = { ...inicial, foto_path: foto ? 'clinica-sintetica/edicao-sintetica/imagem.png' : null }
  const chamadas: Record<string, unknown>[] = []
  await page.clock.setFixedTime(new Date('2026-09-26T12:00:00Z'))
  await page.route('**/*', async (route) => {
    const url = new URL(route.request().url())
    if (url.hostname === '127.0.0.1' || url.hostname.endsWith('googleapis.com') || url.hostname.endsWith('gstatic.com')) return route.continue()
    if (url.hostname !== 'operacional.synthetic.invalid') return route.abort()
    if (url.pathname.includes('/storage/v1/object/')) {
      expect(route.request().method()).toBe('GET')
      expect(route.request().headers()['x-clinica-id']).toBe('clinica-sintetica')
      return route.fulfill({ contentType: 'image/png', body: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9p0AAAAASUVORK5CYII=', 'base64') })
    }
    if (url.pathname.endsWith('/pacientes')) {
      expect(route.request().method()).toBe('GET') // nenhum INSERT ou UPDATE direto
      expect(url.searchParams.get('select')).not.toMatch(/cpf/)
      const clinic = url.searchParams.get('clinica_id')
      const detalhe = url.searchParams.has('id')
      if (clinic === 'eq.clinica-b') return route.fulfill({ contentType: 'application/json', headers: { 'access-control-expose-headers': 'content-range', 'content-range': '*/0' }, body: '[]' })
      paciente.clinica_id = clinic?.slice(3) ?? paciente.clinica_id
      return route.fulfill({ contentType: 'application/json', headers: { 'access-control-expose-headers': 'content-range', 'content-range': '0-0/1' }, body: JSON.stringify(detalhe ? paciente : [paciente]) })
    }
    if (url.pathname.endsWith('/rpc/paciente_responsavel_legal_resumo')) return route.fulfill({ contentType: 'application/json', body: JSON.stringify(comResponsavel ? [{ id: 'r', nome_completo: 'Responsável Sintético', vinculo: 'Mãe', telefone: '77900000011' }] : []) })
    if (url.pathname.endsWith('/rpc/paciente_cpf_pendente')) return route.fulfill({ contentType: 'application/json', body: 'false' })
    if (url.pathname.endsWith('/rpc/paciente_editar_administrativo')) {
      const payload = route.request().postDataJSON(); chamadas.push(payload)
      expect(payload.p_paciente_id).toBe(inicial.id)
      expect(payload.p_clinica_id).toBe(paciente.clinica_id)
      expect(payload.p_updated_at).toBe(inicial.updated_at)
      for (const campo of ['id', 'clinica_id', 'cpf_hash', 'cpf_encrypted', 'foto_path', 'created_at', 'created_by']) expect(payload.p_alteracoes).not.toHaveProperty(campo)
      if (erro) return route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ code: erro }) })
      paciente = { ...paciente, ...payload.p_alteracoes, updated_at: '2026-09-26T12:00:00Z' }
      return route.fulfill({ contentType: 'application/json', body: JSON.stringify([paciente]) })
    }
    throw new Error(`Operação sintética inesperada: ${url.pathname}`)
  })
  return chamadas
}
async function abrir(page: Page) {
  await page.getByRole('button', { name: 'Ver resumo de Ana Demonstração' }).click()
  await page.getByRole('button', { name: 'Editar cadastro' }).click()
  await expect(page.getByLabel('Nome completo', { exact: true })).toHaveValue(inicial.nome_completo)
}
test('Editar na tabela abre o mesmo formulário sem selecionar o resumo; salva e reabre', async ({ page }, info) => {
  const chamadas = await preparar(page)
  await page.goto('/tests/operacional/pacientes-pagina.html')
  await expect(page.locator('[role="columnheader"]').filter({ hasText: 'Ações' })).toHaveCount(1)
  const editar = page.getByRole('button', { name: 'Editar Ana Demonstração' })
  await expect(editar).toBeVisible()
  await page.screenshot({ path: `scratch/pacientes-edicao-20260926/tabela-editar-${info.project.name}.png`, fullPage: true })
  await editar.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog', { name: 'Editar paciente' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Resumo do cadastro' })).toHaveCount(0)
  await expect(page.getByLabel('Nome completo', { exact: true })).toHaveValue(inicial.nome_completo)
  await page.getByRole('button', { name: 'Endereço & Contatos', exact: true }).click()
  await page.getByLabel('Telefone / WhatsApp', { exact: true }).fill('77900000098')
  await page.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(page.getByRole('dialog', { name: 'Editar paciente' })).toHaveCount(0)
  expect(chamadas).toHaveLength(1)
  await page.reload()
  await page.getByRole('button', { name: 'Editar Ana Demonstração' }).click()
  await page.getByRole('button', { name: 'Endereço & Contatos', exact: true }).click()
  await expect(page.getByLabel('Telefone / WhatsApp', { exact: true })).toHaveValue('(77) 90000-0098')
})
test('edição preenche, preserva e atualiza mesmo ID sem INSERT; capturas', async ({ page }, info) => {
  // Este é o primeiro acesso ao Vite sintético: a compilação fria no Windows
  // pode exceder o limite padrão de 30 s antes de qualquer asserção.
  test.setTimeout(90_000)
  const chamadas = await preparar(page)
  await page.goto('/tests/operacional/pacientes-pagina.html')
  await page.getByRole('button', { name: 'Ver resumo de Ana Demonstração' }).click()
  await page.screenshot({ path: `scratch/pacientes-edicao-20260926/resumo-${info.project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Editar cadastro' }).click()
  await expect(page.getByLabel('Nome completo', { exact: true })).toHaveValue(inicial.nome_completo)
  await expect(page.getByLabel('Idade', { exact: true })).toHaveValue('Não determinada')
  await expect(page.getByRole('dialog', { name: 'Editar paciente' })).toContainText('Responsável Sintético')
  await page.screenshot({ path: `scratch/pacientes-edicao-20260926/identificacao-${info.project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Endereço & Contatos', exact: true }).click()
  await expect(page.getByLabel('Endereço completo')).toHaveValue(inicial.endereco)
  await page.getByLabel('Telefone / WhatsApp', { exact: true }).fill('77900000099')
  await page.getByRole('button', { name: 'Voltar à Identificação' }).click()
  await expect(page.getByLabel('Nome completo', { exact: true })).toHaveValue(inicial.nome_completo)
  await page.getByRole('button', { name: 'Endereço & Contatos', exact: true }).click()
  await expect(page.getByLabel('Telefone / WhatsApp', { exact: true })).toHaveValue('(77) 90000-0099')
  await page.screenshot({ path: `scratch/pacientes-edicao-20260926/contatos-${info.project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(page.getByRole('dialog', { name: 'Editar paciente' })).toHaveCount(0)
  expect(chamadas).toHaveLength(1)
  expect(chamadas[0].p_alteracoes).toEqual({ telefone: '(77) 90000-0099' })
  expect(chamadas[0].p_responsavel).toBeNull()
  await expect(page.getByRole('heading', { name: 'Resumo do cadastro' })).toBeVisible()
  await expect(page.locator('.pacientes-resumo')).toContainText('(77) 90000-0099')
  await expect(page.locator('.pacientes-endereco-literal')).toHaveText(inicial.endereco)
})

test('foto privada existente permanece entre etapas e após resposta de edição', async ({ page }) => {
  await page.addInitScript(() => {
    const header = btoa(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).replaceAll('=', '')
    const body = btoa(JSON.stringify({ sub: '00000000-0000-4000-8000-000000000001', role: 'authenticated', exp: 1990000000 })).replaceAll('=', '')
    localStorage.setItem('sb-operacional-auth-token', JSON.stringify({ access_token: `${header}.${body}.assinatura-sintetica`, refresh_token: 'sintetico', token_type: 'bearer', expires_at: 1990000000, user: { id: '00000000-0000-4000-8000-000000000001', aud: 'authenticated', role: 'authenticated' } }))
  })
  await preparar(page, undefined, true, true)
  await page.goto('/tests/operacional/pacientes-pagina.html'); await abrir(page)
  const foto = page.locator('.paciente-edicao img')
  await expect(foto).toHaveAttribute('src', /^blob:/)
  const fonte = await foto.getAttribute('src')
  await page.getByRole('button', { name: 'Endereço & Contatos', exact: true }).click()
  await page.getByLabel('Telefone / WhatsApp', { exact: true }).fill('77900000099')
  await page.getByRole('button', { name: 'Voltar à Identificação' }).click()
  await expect(foto).toHaveAttribute('src', fonte!)
  await page.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(page.getByRole('dialog', { name: 'Editar paciente' })).toHaveCount(0)
  await expect(page.locator('.pacientes-resumo img')).toHaveAttribute('src', /^blob:/)
})
test('validação, cancelamento, grafia e ausência de gravação', async ({ page }) => {
  const chamadas = await preparar(page)
  await page.goto('/tests/operacional/pacientes-pagina.html'); await abrir(page)
  await page.getByLabel('Nome completo', { exact: true }).fill('MARIA DA CONCEIÇÃO')
  await expect(page.getByLabel('Nome completo', { exact: true })).toHaveValue('Maria da Conceição')
  await page.getByLabel('Nome completo', { exact: true }).fill('')
  await page.getByLabel('Nome completo', { exact: true }).fill('JOÃO DOS SANTOS')
  await expect(page.getByLabel('Nome completo', { exact: true })).toHaveValue('João dos Santos')
  await page.getByLabel('Preservar grafia excepcional').check()
  await page.getByLabel('Nome completo', { exact: true }).fill('João McDonald')
  await page.getByRole('button', { name: 'Endereço & Contatos', exact: true }).click()
  await page.getByLabel('E-mail', { exact: true }).fill('invalido')
  await page.getByRole('button', { name: 'Voltar à Identificação' }).click()
  await page.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(page.getByRole('alert')).toContainText('e-mail válido')
  await expect(page.getByLabel('E-mail', { exact: true })).toBeVisible()
  await expect(page.getByLabel('E-mail', { exact: true })).toBeFocused()
  expect(chamadas).toHaveLength(0)
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await page.getByRole('button', { name: 'Continuar editando' }).click()
  await expect(page.getByLabel('E-mail', { exact: true })).toHaveValue('invalido')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Descartar alterações' }).click()
  expect(chamadas).toHaveLength(0)
})
test('conflito, contrato ausente e autorização negada preservam edição', async ({ page }) => {
  for (const [codigo, mensagem] of [['PT409', 'outra operação'], ['PGRST202', 'ainda não está disponível'], ['42501', 'autorizar']]) {
    await page.unrouteAll()
    const chamadas = await preparar(page, codigo)
    await page.goto('/tests/operacional/pacientes-pagina.html'); await abrir(page)
    await page.getByLabel('Nome completo', { exact: true }).fill('Outro Exemplo')
    await page.getByRole('button', { name: 'Salvar alterações' }).click()
    await expect(page.getByRole('alert')).toContainText(mensagem)
    await expect(page.getByLabel('Nome completo', { exact: true })).toHaveValue('Outro Exemplo')
    expect(chamadas).toHaveLength(1)
    await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
    await page.getByRole('button', { name: 'Descartar alterações' }).click()
  }
})
test('correção para menor exige responsável atomicamente sem criar novo paciente', async ({ page }) => {
  const chamadas = await preparar(page, undefined, false)
  await page.goto('/tests/operacional/pacientes-pagina.html'); await abrir(page)
  await page.getByLabel('Data de nascimento', { exact: true }).fill('2015-01-01')
  await page.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(page.getByRole('alert')).toContainText('responsável legal')
  expect(chamadas).toHaveLength(0)
  await page.getByLabel('Nome completo do responsável', { exact: true }).fill('Responsável Sintético')
  await page.getByLabel('Vínculo com o paciente', { exact: true }).fill('Mãe')
  await page.getByLabel('Telefone / WhatsApp do responsável', { exact: true }).fill('77900000011')
  await page.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(page.getByRole('dialog', { name: 'Editar paciente' })).toHaveCount(0)
  expect(chamadas).toHaveLength(1)
  expect(chamadas[0].p_alteracoes).toEqual({ data_nascimento: '2015-01-01' })
  expect(chamadas[0].p_responsavel).toMatchObject({ nome_completo: 'Responsável Sintético', cpf: '' })
})

test('preserva busca e ordenação; informa saída dos critérios após editar', async ({ page }) => {
  await preparar(page)
  await page.goto('/tests/operacional/pacientes-pagina.html')
  await page.getByRole('searchbox').fill('Ana')
  await page.getByRole('combobox', { name: 'Ordenar por' }).selectOption('nome_desc')
  await abrir(page)
  await page.getByLabel('Nome completo', { exact: true }).fill('Beatriz Demonstração')
  await page.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(page.getByRole('dialog', { name: 'Editar paciente' })).toHaveCount(0)
  await expect(page.getByText('Cadastro atualizado. O paciente deixou de corresponder à busca ou aos filtros atuais.')).toBeVisible()
  await expect(page.getByRole('searchbox')).toHaveValue('Ana')
  await expect(page.getByRole('combobox', { name: 'Ordenar por' })).toHaveValue('nome_desc')
  await expect(page.getByRole('heading', { name: 'Resumo do cadastro' })).toHaveCount(0)
})

test('troca de clínica invalida edição sem gravar na nova unidade', async ({ page }) => {
  const chamadas = await preparar(page)
  await page.goto('/tests/operacional/pacientes-contexto.html'); await abrir(page)
  await page.getByLabel('Nome completo', { exact: true }).fill('Não Enviar')
  // Mudança externa de contexto, inclusive enquanto o dialog torna o fundo inerte.
  await page.getByRole('button', { name: 'Trocar para Clínica B' }).evaluate((el: HTMLButtonElement) => el.click())
  await expect(page.getByRole('dialog', { name: 'Editar paciente' })).toHaveCount(0)
  await expect(page.getByText('Não Enviar')).toHaveCount(0)
  expect(chamadas).toHaveLength(0)
})
