import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

const url = '/tests/operacional/recepcao-preview.html'
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => { if (!localStorage.getItem('clinica-patricia:tema')) localStorage.setItem('clinica-patricia:tema', 'claro'); localStorage.removeItem('clinica:sidebar:expanded') })
  await page.route('https://**/*', route => route.abort())
})
async function abrir(page: import('@playwright/test').Page, query = '') {
  await page.goto(url + query, { waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('heading', { name: 'Movimento de hoje' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Atualizar', exact: true })).toBeEnabled()
}
async function captura(page: import('@playwright/test').Page, nome: string) {
  await mkdir('scratch/recepcao-preview/capturas', { recursive: true })
  await page.screenshot({ path: `scratch/recepcao-preview/capturas/${nome}.png`, fullPage: true })
}
test('composição, espera por chegada, estados oficiais, temas e capturas', async ({ page }, info) => {
  const externas: string[] = []; const erros: string[] = []
  // O antivírus do Windows injeta requisições próprias; elas não são serviços da proposta.
  page.on('request', r => { const host = new URL(r.url()).hostname; if (!r.url().startsWith('http://127.0.0.1:4193') && !host.endsWith('.kaspersky-labs.com')) externas.push(r.url()) })
  page.on('pageerror', e => erros.push(e.message))
  await abrir(page)
  const indicadores = page.getByRole('region', { name: 'Indicadores do dia' })
  await expect(indicadores).toContainText('18'); await expect(indicadores).toContainText('3')
  await expect(page.getByTestId('registro')).toHaveCount(3)
  await expect(page.getByTestId('registro').first()).toContainText('25 min de espera')
  await expect(page.getByTestId('registro').last()).toContainText('Parcialmente estornado')
  await expect(page.getByTestId('registro').last().getByRole('button')).toHaveText('Conferir')
  await expect(page.getByText('18 agendamentos / 17 pacientes distintos', { exact: false })).toBeVisible()
  if (info.project.name !== 'desktop') {
    await expect(page.getByRole('button', { name: /Caixa do turno/ })).toHaveAttribute('aria-expanded', 'false')
    await expect(page.getByRole('button', { name: /Pendências cadastrais/ })).toHaveAttribute('aria-expanded', 'false')
  }
  const fila = await page.getByRole('heading', { name: 'Movimento de hoje' }).boundingBox()
  expect(fila!.y).toBeLessThan(info.project.name === 'mobile' ? 640 : 600)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await captura(page, `${info.project.name}-claro`)
  await page.getByRole('button', { name: 'Ativar modo escuro' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'escuro')
  await captura(page, `${info.project.name}-escuro`)
  await page.reload(); await expect(page.locator('html')).toHaveAttribute('data-theme', 'escuro')
  expect(externas).toEqual([]); expect(erros).toEqual([])
})
test('busca nominal, filtro, abas por teclado e ações somente simuladas', async ({ page }) => {
  await abrir(page)
  const tab = page.getByRole('tab', { name: /Aguardando/ }); await tab.focus(); await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: /Previstos/ })).toBeFocused()
  await page.keyboard.press('End'); await expect(page.getByRole('tab', { name: /Concluídos/ })).toBeFocused()
  const limite = await page.getByRole('tab', { name: /Concluídos/ }).boundingBox()
  expect(limite!.x + limite!.width).toBeLessThanOrEqual(await page.evaluate(() => innerWidth))
  await page.keyboard.press('Home'); await expect(tab).toBeFocused()
  await page.getByLabel('Buscar paciente').fill('bruno'); await expect(page.getByTestId('registro')).toHaveCount(1)
  await page.getByTestId('registro').getByRole('button', { name: 'Receber' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Demonstração' })).toContainText('Ação simulada')
  await page.getByLabel('Buscar paciente').fill(''); await page.getByLabel('Filtrar por profissional').selectOption('2')
  await expect(page.getByTestId('registro')).toHaveCount(1); await expect(page.getByTestId('registro')).toContainText('Carla Dantas')
  await page.getByRole('region', { name: 'Próximas chegadas' }).getByRole('button', { name: 'Registrar chegada' }).first().click()
  await expect(page.getByRole('status').filter({ hasText: 'Demonstração' })).toContainText('Registrar chegada')
  await expect(page.getByRole('tab', { name: /Aguardando/ })).toContainText('3')
})
test('horário passado sem chegada preserva previsão e não fabrica espera ou falta', async ({ page }, info) => {
  await abrir(page, '?cenario=passado')
  await page.getByRole('button', { name: 'Conferir', exact: true }).first().click()
  await expect(page.getByRole('tab', { name: /Previstos/ })).toHaveAttribute('aria-selected', 'true')
  const semChegada = page.getByTestId('registro').filter({ hasText: /Pedro Santos|Rosa Melo/ })
  await expect(semChegada).toHaveCount(2)
  for (const linha of await semChegada.all()) { await expect(linha).toContainText('Sem chegada • conferir'); await expect(linha).not.toContainText('min de espera') }
  await expect(page.locator('.rp')).not.toContainText('Faltou')
  await captura(page, `${info.project.name}-sem-chegada`)
})
test('dia vazio é distinto de falha e financeiro falho não vira zero ou pendente', async ({ page }, info) => {
  await abrir(page, '?cenario=vazio'); await expect(page.getByText('O dia está livre por aqui')).toBeVisible()
  await captura(page, `${info.project.name}-vazio`)
  await abrir(page, '?cenario=falha'); await expect(page.getByRole('tabpanel').getByRole('alert')).toContainText('Movimento indisponível')
  await expect(page.locator('.rp-metrics')).not.toContainText('0')
  await captura(page, `${info.project.name}-falha`)
  await abrir(page, '?cenario=financeiro')
  const caixa = page.getByRole('region', { name: 'Caixa do turno' })
  if (await caixa.getByRole('button', { name: /Caixa do turno/ }).getAttribute('aria-expanded') === 'false') await caixa.getByRole('button', { name: /Caixa do turno/ }).click()
  await expect(caixa).toContainText('Caixa indisponível'); await expect(caixa).not.toContainText('R$')
  await expect(page.locator('.rp-records')).not.toContainText('Sem recebimento registrado')
  await expect(page.locator('.rp-records')).not.toContainText('Pendente')
  await expect(page.getByTestId('registro').first()).toContainText('Informação indisponível')
  await captura(page, `${info.project.name}-falha-financeira`)
})
test('parcial informado pede conferência, bruto e saldo distintos, último registro acessível', async ({ page }, info) => {
  await abrir(page, '?cenario=parcial')
  const parcial = page.getByTestId('registro').filter({ hasText: 'Bruno Tavares' })
  await expect(parcial).toContainText('Parcial informado • conferir'); await expect(parcial.getByRole('button')).toHaveText('Conferir')
  await captura(page, `${info.project.name}-parcial`)
  const caixa = page.getByRole('region', { name: 'Caixa do turno' })
  if (await caixa.getByRole('button', { name: /Caixa do turno/ }).getAttribute('aria-expanded') === 'false') await caixa.getByRole('button', { name: /Caixa do turno/ }).click()
  await expect(caixa).toContainText('R$ 1.450,00'); await expect(caixa).toContainText('R$ 570,00')
  await caixa.getByRole('button', { name: 'Ocultar valores simulados' }).click(); await expect(caixa).not.toContainText('R$')
  await page.getByRole('tab', { name: /Concluídos/ }).click()
  const ultimo = page.getByTestId('registro').last().getByRole('button'); await ultimo.scrollIntoViewIfNeeded(); await ultimo.focus()
  const box = await ultimo.boundingBox(); expect(box!.y + box!.height).toBeLessThanOrEqual(page.viewportSize()!.height)
  await page.keyboard.press('Enter'); await expect(page.getByText(/Ação simulada: Ver cadastro/)).toBeVisible()
})
test('resposta atrasada não reaparece após trocar clínica; desatualização explícita', async ({ page }) => {
  await abrir(page, '?atraso')
  await page.getByRole('button', { name: 'Atualizar', exact: true }).click()
  await page.getByText('Cenários de demonstração', { exact: true }).click()
  await page.getByLabel('Unidade simulada').selectOption('previa-ipupiara')
  await expect(page.getByTestId('registro')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Atualizar', exact: true })).toBeEnabled()
  await expect(page.getByTestId('registro').first()).toContainText('Ana Moura (I)')
  await page.getByLabel('Cenário da prévia').selectOption('desatualizado')
  await expect(page.getByRole('button', { name: 'Atualizar', exact: true })).toBeEnabled()
  await expect(page.getByRole('heading', { name: 'Dados desatualizados', exact: true })).toBeVisible()
  await expect(page.getByTestId('registro').first()).toContainText('Espera indisponível')
  await page.getByRole('button', { name: 'Atualizar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Dados desatualizados', exact: true })).toHaveCount(0)
})
test('CPF exige modalidade exata, não filtra por fragmentos, menu móvel existente preservado', async ({ page }, info) => {
  await abrir(page)
  await page.getByLabel('Modalidade da busca').selectOption('cpf')
  await page.getByLabel('CPF exato', { exact: true }).fill('123')
  await expect(page.getByRole('button', { name: 'Buscar CPF' })).toBeDisabled()
  await expect(page.getByTestId('registro')).toHaveCount(0)
  await expect(page.getByText('Busca por CPF simulada.', { exact: false })).toBeVisible()
  if (info.project.name === 'mobile') {
    await page.getByRole('button', { name: 'Abrir menu', exact: true }).click()
    const menu = page.getByRole('dialog'); await expect(menu).toBeVisible()
    await menu.getByRole('link', { name: 'Agenda', exact: true }).click()
    await expect(menu).toHaveCount(0); await expect(page.getByRole('heading', { name: 'Destino simulado' })).toBeVisible()
    await page.getByRole('button', { name: 'Voltar ao painel da recepção' }).click()
    await expect(page.getByRole('heading', { name: 'Movimento de hoje' })).toBeVisible()
  }
})
