import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'

const versao = (JSON.parse(readFileSync('package.json', 'utf8')) as { version: string }).version

test('papel e página Sobre acompanham a clínica e os metadados do build', async ({ page }, info) => {
  await page.goto('/tests/operacional/shell.html?papel=proprietaria')
  if (info.project.name !== 'desktop') await page.getByRole('button', { name: 'Abrir menu' }).click()
  await expect(page.getByText('Visão de proprietário(a)')).toBeVisible()
  await expect(page.locator('#app-sidebar').getByText('Proprietário(a)', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Sobre o sistema' }).click()
  await expect(page.getByRole('heading', { name: 'Sobre o sistema' })).toBeVisible()
  await expect(page.getByText('Clínica Demonstração', { exact: true }).last()).toBeVisible()
  await expect(page.getByText(versao, { exact: true })).toBeVisible()
  await expect(page.getByText('Versão em execução', { exact: true })).toBeVisible()
  await expect(page.getByText('Em desenvolvimento', { exact: true })).toBeVisible()
  await expect(page.getByText('Melhorias em desenvolvimento')).toBeVisible()
  await expect(page.getByText('Desenvolvido por Eduardo Campos')).toBeVisible()
  await expect(page.getByText('Vencer Digital', { exact: true })).toBeVisible()
  await expect(page.getByText('O histórico será atualizado a partir do primeiro lançamento.')).toBeVisible()
  await expect(page.getByText(/Versão local/)).toHaveCount(0)
  const logo = page.getByRole('img', { name: 'Vencer Digital — Sistemas • Sites • Soluções com IA' })
  await expect(logo).toBeVisible()
  expect(await logo.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0)
  await expect(page.getByRole('link', { name: 'Conversar pelo WhatsApp — (77) 99129-0375' })).toHaveAttribute('href', 'https://wa.me/5577991290375')
  await expect(page.getByRole('link', { name: 'Instagram — @vencerdigital.ia' })).toHaveAttribute('href', 'https://www.instagram.com/vencerdigital.ia/')
  if (info.project.name !== 'desktop') await expect(page.locator('#app-sidebar')).not.toBeInViewport()
  await page.screenshot({ path: `scratch/sobre-sistema-${info.project.name}.png`, fullPage: true })
  await page.getByText('Tecnologia e informações técnicas').click()
  await expect(page.getByText('Commit de origem')).toBeVisible()
  await expect(page.getByText('Alterações locais na compilação')).toBeVisible()
  await page.getByRole('combobox', { name: 'Selecionar clínica' }).selectOption('clinica-b')
  await expect(page.getByText('Clínica Segunda Unidade', { exact: true }).last()).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Sobre o sistema' })).toBeVisible()
})

test('Sobre acessível por teclado sem depender de dados reais', async ({ page }, info) => {
  await page.goto('/tests/operacional/shell.html?papel=recepcao')
  if (info.project.name !== 'desktop') await page.getByRole('button', { name: 'Abrir menu' }).click()
  const sobre = page.getByRole('button', { name: 'Sobre o sistema' })
  await sobre.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Sobre o sistema' })).toBeVisible()
  await expect(sobre).toHaveAttribute('aria-current', 'page')
  await page.getByRole('button', { name: 'Ativar modo escuro' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'escuro')
  await expect(page.getByRole('img', { name: 'Vencer Digital — Sistemas • Sites • Soluções com IA' })).toBeVisible()
  await expect(page.locator('.sobre-logo-superficie')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.screenshot({ path: `scratch/sobre-sistema-escuro-${info.project.name}.png`, fullPage: true })
})
