import { expect, test } from '@playwright/test'
import { abrirMenu, fecharMenu, clinicas, preparar } from './dashboard-fixture'

for (const unidade of ['brotas', 'ipupiara'] as const) {
  test(`dashboard sem cartões explicativos — ${unidade}`, async ({ page }, info) => {
    await preparar(page)
    await page.goto(`/sistema/${unidade}/dashboard`)
    await expect(page.getByText('Nenhum agendamento restante hoje.')).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Indicadores financeiros' })).toHaveCount(0)
    await page.screenshot({ path: `scratch/dashboard-proprietaria/${process.env.DASHBOARD_CAPTURA_ANTES === '1' ? 'antes' : 'depois'}-${unidade}-${info.project.name}.png`, fullPage: true })
  })

  test(`menu, cadastros e recarga — ${unidade}`, async ({ page }) => {
    const { escritas } = await preparar(page)
    await page.goto(`/sistema/${unidade}/dashboard`)
    await expect(page.getByRole('region', { name: 'Administração da clínica' })).toHaveCount(0)
    await abrirMenu(page)
    const administracao = page.getByRole('navigation', { name: 'Navegação principal' })
    await expect(administracao).toBeVisible()
    await expect(administracao.getByRole('link', { name: 'Equipe', exact: true })).toHaveAttribute('href', `/sistema/${unidade}/equipe`)
    await expect(administracao.getByRole('link', { name: 'Financeiro', exact: true })).toHaveAttribute('href', `/sistema/${unidade}/financeiro`)
    await expect(page.locator('main')).not.toContainText('R$')
    await administracao.getByRole('link', { name: 'Equipe', exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/sistema/${unidade}/equipe$`))
    await expect(page.getByRole('heading', { name: 'Cadastros', exact: true })).toBeVisible()
    const abas = page.getByRole('navigation', { name: 'Seções de Cadastros' })
    for (const nome of ['Equipe & acessos', 'Especialidades', 'Profissionais', 'Serviços']) await expect(abas.getByRole('button', { name: nome, exact: true })).toBeVisible()
    await abas.getByRole('button', { name: 'Especialidades', exact: true }).click()
    await expect(page.getByText('Especialidade Sintética', { exact: true })).toBeVisible()
    await abas.getByRole('button', { name: 'Profissionais', exact: true }).click()
    await expect(abas.getByRole('button', { name: 'Profissionais', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await abas.getByRole('button', { name: 'Serviços', exact: true }).click()
    await expect(page.getByText(`Serviço Sintético Clínica ${unidade === 'brotas' ? 'Brotas' : 'Ipupiara'}`, { exact: true }).filter({ visible: true })).toBeVisible()
    await expect(page.getByText('R$ 123,45').filter({ visible: true })).toBeVisible()
    await page.reload()
    await expect(page.getByRole('heading', { name: 'Cadastros', exact: true })).toBeVisible()
    await expect(page).toHaveURL(new RegExp(`/sistema/${unidade}/equipe$`))
    await page.goBack()
    await abrirMenu(page)
    await expect(administracao).toBeVisible()
    await page.reload()
    await abrirMenu(page)
    await expect(administracao).toBeVisible()
    await administracao.getByRole('link', { name: 'Financeiro', exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/sistema/${unidade}/financeiro$`))
    await expect(page.getByRole('navigation', { name: 'Áreas do Financeiro' })).toBeVisible()
    await expect(page.getByRole('alert')).toContainText('Indicadores indisponíveis')
    expect(escritas).toEqual([])
  })
}

test('troca de clínica atualiza destinos e consultas, sem misturar serviços', async ({ page }) => {
  const { escritas } = await preparar(page)
  await page.goto('/sistema/brotas/dashboard')
  await abrirMenu(page)
  const cadastros = page.getByRole('link', { name: 'Equipe', exact: true })
  await expect(cadastros).toHaveAttribute('href', '/sistema/brotas/equipe')
  await fecharMenu(page)
  await page.getByRole('combobox', { name: 'Selecionar clínica', exact: true }).selectOption(clinicas[1].id)
  await expect(page).toHaveURL(/\/sistema\/ipupiara\/dashboard$/)
  await abrirMenu(page)
  await expect(cadastros).toHaveAttribute('href', '/sistema/ipupiara/equipe')
  await cadastros.click()
  await page.getByRole('button', { name: 'Serviços', exact: true }).click()
  await expect(page.getByText('Serviço Sintético Clínica Ipupiara', { exact: true }).filter({ visible: true })).toBeVisible()
  await expect(page.getByText('Serviço Sintético Clínica Brotas', { exact: true })).toHaveCount(0)
  expect(escritas).toEqual([])
})

for (const papel of ['recepcao', 'medico'] as const) test(`menu e restrição de rota preservados para ${papel}`, async ({ page }) => {
  await preparar(page, papel)
  await page.goto('/sistema/brotas/dashboard')
  await expect(page.locator('.app-shell-header')).toBeVisible()
  await expect(page.getByRole('region', { name: 'Administração da clínica' })).toHaveCount(0)
  await abrirMenu(page)
  await expect(page.getByRole('link', { name: 'Financeiro', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Equipe', exact: true })).toHaveCount(papel === 'recepcao' ? 1 : 0)
  await page.goto('/sistema/brotas/configuracoes')
  await expect(page.getByRole('alert')).toContainText('Página não autorizada')
})

test('erro no próximo paciente mantém menu e aviso distinto do vazio', async ({ page }) => {
  await preparar(page, 'proprietaria', 'erro-agenda')
  await page.goto('/sistema/ipupiara/dashboard')
  await expect(page.getByRole('status')).toContainText('Próximo paciente indisponível')
  await abrirMenu(page)
  await expect(page.getByRole('link', { name: 'Equipe', exact: true })).toBeVisible()
  await expect(page.getByText('Nenhum agendamento restante hoje.')).toHaveCount(0)
})

test('carregamento de acesso não mostra acessos pelo menu antes de confirmar o papel', async ({ page }) => {
  await preparar(page, 'proprietaria', 'lento')
  await page.goto('/sistema/brotas/dashboard')
  await expect(page.getByRole('status')).toContainText('Verificando acesso')
  await expect(page.getByRole('link', { name: 'Equipe', exact: true })).toHaveCount(0)
  await abrirMenu(page)
  await expect(page.getByRole('link', { name: 'Equipe', exact: true })).toBeVisible()
})

test('falha de autorização não vira painel vazio nem expõe acessos pelo menu', async ({ page }) => {
  await preparar(page, 'proprietaria', 'erro-acesso')
  await page.goto('/sistema/brotas/dashboard')
  await expect(page.getByRole('alert')).toContainText('Isso não confirma ausência de vínculo')
  await expect(page.getByRole('link', { name: 'Equipe', exact: true })).toHaveCount(0)
})

test('acessos pelo menu alcançáveis no tema escuro, teclado e sem transbordamento', async ({ page }) => {
  await preparar(page)
  await page.goto('/sistema/ipupiara/dashboard')
  await expect(page.locator('.app-shell-header')).toBeVisible()
  await page.getByRole('button', { name: 'Ativar modo escuro' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'escuro')
  await abrirMenu(page)
  const cadastros = page.getByRole('link', { name: 'Equipe', exact: true })
  await expect(cadastros).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await cadastros.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Cadastros', exact: true })).toBeVisible()
})
