import { test, expect, type Page } from '@playwright/test'
const A = '22222222-2222-4222-8222-222222222222', B = '33333333-3333-4333-8333-333333333333', M = '55555555-5555-4555-8555-555555555555'
const pagina = '/tests/acesso-direto/preview.html'
test('reserva expirada retoma preparação sem substituir conta nem refazer pessoa', async ({ page }) => { const c = await simular(page); await page.goto(`${pagina}?habilitado=1&modo=substituir&reservadaExpirada=1`); await expect(page.getByText('Credencial temporária expirada')).toBeVisible(); await page.getByRole('button', { name: 'Retomar preparação do acesso' }).click(); await expect(page.getByRole('dialog', { name: 'Acesso preparado' })).toBeVisible(); expect(c.diretos).toBe(1); expect(c.substituicoes).toBe(0); expect(c.pessoas).toBe(0) })
async function simular(page: Page, op: { falha?: string; estado?: string; sessao?: boolean } = {}) {
  const contagem = { pessoas: 0, diretos: 0, convites: 0, ativacoes: 0, tokens: 0, substituicoes: 0, escopos: [] as unknown[], chaves: [] as unknown[] }
  let falhou = false, ativa = false
  const user = { id: '11111111-1111-4111-8111-111111111111', email: 'titular@example.invalid', aud: 'authenticated' }
  const token = [Buffer.from('{"alg":"HS256","typ":"JWT"}').toString('base64url'), Buffer.from(JSON.stringify({ sub: user.id, exp: Math.floor(Date.now()/1000)+3600, aud: 'authenticated', session_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' })).toString('base64url'), 'synthetic'].join('.')
  if (op.sessao) await page.addInitScript(({ user, token }) => localStorage.setItem('sb-financeiro-auth-token', JSON.stringify({ access_token: token, refresh_token: 'synthetic', expires_at: Math.floor(Date.now()/1000)+3600, user })), { user, token })
  await page.route('**/*', async route => {
    const request = route.request(), url = new URL(request.url())
    if (url.hostname === '127.0.0.1') return route.continue()
    if (url.hostname !== 'financeiro.synthetic.invalid') return route.abort()
    const headers = { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*', 'access-control-allow-methods': 'GET,POST,OPTIONS' }
    if (request.method() === 'OPTIONS') return route.fulfill({ status: 204, headers })
    const json = (data: unknown, status = 200) => route.fulfill({ status, headers, contentType: 'application/json', body: JSON.stringify(data) })
    if (url.pathname.endsWith('/auth/v1/user')) return json(user)
    if (url.pathname.endsWith('/auth/v1/token')) { contagem.tokens++; return json({ access_token: token, refresh_token: 'synthetic', expires_in: 3600, token_type: 'bearer', user }) }
    if (url.pathname.endsWith('/auth/v1/logout')) return route.fulfill({ status: 204, headers })
    if (url.pathname.endsWith('/rpc/acesso_direto_estado')) return op.estado === 'erro' ? json({ code: 'PGRST202' }, 404) : json({ estado: ativa ? 'normal' : op.estado ?? 'normal' })
    if (url.pathname.endsWith('/rpc/equipe_listar')) return json([])
    if (url.pathname.endsWith('/clinicas')) return json([{ id: A, nome: 'Clínica Brotas' }, { id: B, nome: 'Clínica Ipupiara' }])
    if (url.pathname.endsWith('/especialidades')) return json([])
    if (url.pathname.endsWith('/rpc/equipe_salvar')) { contagem.pessoas++; return json(M) }
    if (url.pathname.endsWith('/functions/v1/equipe-acessos')) { contagem.convites++; const b = request.postDataJSON(); contagem.escopos.push(b.clinicasPapeis); return json({ id: M, status: 'enviado' }) }
    if (url.pathname.endsWith('/functions/v1/equipe-acesso-direto')) {
      const b = request.postDataJSON()
      if (b.acao === 'ativar') { contagem.ativacoes++; if (op.falha) return json({ codigo: op.falha, erro: 'erro sintético' }, 422); ativa = true; return json({ estado: 'ativa' }) }
      if (b.acao === 'substituir') { contagem.substituicoes++; return json({ operacaoId: M, email: user.email, senhaTemporaria: 'SenhaFicticiaSubstituta!28', expiraEm: '2026-10-09T22:00:00Z' }) }
      contagem.diretos++; contagem.chaves.push(b.chaveIdempotencia); contagem.escopos.push(b.clinicasPapeis)
      if (op.falha && !falhou) { falhou = true; return json({ codigo: op.falha, erro: 'erro sintético' }, 422) }
      return json({ operacaoId: M, email: b.email ?? user.email, senhaTemporaria: 'SenhaFicticiaParaTeste!927', expiraEm: '2026-10-09T22:00:00Z' })
    }
    return json([])
  })
  return contagem
}
async function abrirNovo(page: Page, habilitado = true) {
  await page.goto(`${pagina}?habilitado=${habilitado ? '1' : '0'}`)
  await page.getByRole('button', { name: 'Novo membro', exact: true }).click()
  await page.getByLabel('Nome completo *').fill('Pessoa Sintética')
  await page.getByLabel('Tipo de função *').selectOption('administrativo')
  await page.getByLabel('Cargo ou função *').selectOption('Recepcionista')
}
async function acesso(page: Page, modo = 'Criar acesso com senha temporária') {
  await page.getByLabel(modo, { exact: true }).check()
  await page.getByLabel('E-mail de login *').fill('titular@example.invalid')
  const secao = page.getByRole('group', { name: 'Clínicas e papéis de acesso *' })
  await secao.getByLabel('Clínica Brotas', { exact: true }).check()
  await page.getByLabel('Papel de acesso em Clínica Brotas').selectOption('recepcao')
}
test('aplicação normal informa backend pendente e não grava no modo temporário', async ({ page }) => { const c = await simular(page); await abrirNovo(page, false); await acesso(page); await expect(page.getByText('Acesso direto ainda indisponível')).toBeVisible(); await expect(page.getByRole('button', { name: 'Salvar pessoa e preparar acesso' })).toBeDisabled(); expect(c.pessoas + c.diretos).toBe(0) })
test('cadastro sem acesso conserva operação única', async ({ page }) => { const c = await simular(page); await abrirNovo(page); await page.getByRole('button', { name: 'Salvar cadastro', exact: true }).click(); await expect(page.getByText('Funcionário cadastrado com sucesso.')).toBeVisible(); expect(c.pessoas).toBe(1); expect(c.diretos + c.convites).toBe(0) })
test('cargo não seleciona papel e não concede outra clínica', async ({ page }) => { const c = await simular(page); await abrirNovo(page); await page.getByLabel('Criar acesso com senha temporária', { exact: true }).check(); await page.getByLabel('E-mail de login *').fill('titular@example.invalid'); await page.getByRole('group', { name: 'Clínicas e papéis de acesso *' }).getByLabel('Clínica Brotas').check(); await expect(page.getByLabel('Papel de acesso em Clínica Brotas')).toHaveValue(''); await page.getByRole('button', { name: 'Salvar pessoa e preparar acesso' }).click(); expect(c.pessoas + c.diretos).toBe(0); await page.getByLabel('Papel de acesso em Clínica Brotas').selectOption('recepcao'); await page.getByRole('button', { name: 'Salvar pessoa e preparar acesso' }).click(); await expect(page.getByRole('dialog', { name: 'Acesso preparado' })).toBeVisible(); expect(c.escopos).toEqual([[{ clinica_id: A, papel: 'recepcao' }]]); expect(c.convites).toBe(0) })
test('convite usa serviço existente, sem senha temporária', async ({ page }) => { const c = await simular(page); await abrirNovo(page); await acesso(page, 'Enviar convite por e-mail'); await page.getByRole('button', { name: 'Salvar pessoa e preparar acesso' }).click(); await expect(page.getByText('Pessoa cadastrada e convite processado. O acesso aguarda o aceite do titular.')).toBeVisible(); expect(c.pessoas).toBe(1); expect(c.convites).toBe(1); expect(c.diretos).toBe(0) })
test('falha parcial preserva ID e chave; retomada não duplica', async ({ page }) => { const c = await simular(page, { falha: 'OPERACAO_NAO_CONFIRMADA' }); await abrirNovo(page); await acesso(page); await page.getByRole('button', { name: 'Salvar pessoa e preparar acesso' }).click(); await expect(page.getByText('Pessoa já salva')).toBeVisible(); await expect(page.getByLabel('Nome completo *')).toBeDisabled(); await page.getByRole('button', { name: 'Retomar acesso e concluir' }).click(); await expect(page.getByRole('dialog', { name: 'Acesso preparado' })).toBeVisible(); expect(c.pessoas).toBe(1); expect(c.diretos).toBe(2); expect(c.chaves[0]).toBe(c.chaves[1]) })
test('conta existente informa vinculação e não apresenta credencial', async ({ page }) => { const c = await simular(page, { falha: 'CONTA_EXISTENTE' }); await abrirNovo(page); await acesso(page); await page.getByRole('button', { name: 'Salvar pessoa e preparar acesso' }).click(); await expect(page.getByText(/Já existe uma conta para esse e-mail/)).toBeVisible(); await expect(page.getByRole('dialog', { name: 'Acesso preparado' })).toHaveCount(0); expect(c.convites).toBe(0) })
test('troca de contexto limpa formulário e credencial', async ({ page }) => { await simular(page); await abrirNovo(page); await acesso(page); await page.getByRole('button', { name: 'Cancelar', exact: true }).click(); await page.getByRole('button', { name: 'Descartar alterações', exact: true }).click(); await page.getByRole('button', { name: 'Trocar contexto sintético' }).click(); await page.getByRole('button', { name: 'Novo membro', exact: true }).click(); await expect(page.getByLabel('Somente cadastrar a pessoa')).toBeChecked(); await expect(page.getByLabel('E-mail de login *')).toHaveCount(0) })
test('credencial só em memória; mostrar, copiar e fechar no computador/celular', async ({ page }, info) => { await simular(page); await page.context().grantPermissions(['clipboard-read', 'clipboard-write']); await page.goto(`${pagina}?modo=credencial`); await expect(page.locator('#credencial-temporaria')).toHaveAttribute('type', 'password'); await page.getByRole('button', { name: 'Mostrar senha', exact: true }).click(); await expect(page.locator('#credencial-temporaria')).toHaveAttribute('type', 'text'); await page.getByRole('button', { name: 'Copiar senha temporária' }).click(); await expect(page.getByRole('status')).toContainText('Senha copiada'); expect(await page.evaluate(() => JSON.stringify({ ...localStorage }))).not.toContain('SenhaFicticia'); await page.screenshot({ path: `scratch/acesso-direto/credencial-${info.project.name}.png` }); await page.getByRole('button', { name: 'Concluir e fechar' }).click(); await expect(page.locator('#credencial-temporaria')).toHaveCount(0) })
test('guarda pendente impede montagem do módulo e F5 mantém primeiro acesso', async ({ page }, info) => { await simular(page, { sessao: true, estado: 'pendente' }); await page.goto(`${pagina}?habilitado=1&modo=guard`); await expect(page.getByRole('heading', { name: 'Defina sua senha pessoal' })).toBeVisible(); await expect(page.getByText('Módulo administrativo sintético')).toHaveCount(0); expect(await page.getAttribute('body', 'data-modulo-montado')).toBeNull(); await page.reload(); await expect(page.getByRole('heading', { name: 'Defina sua senha pessoal' })).toBeVisible(); await page.getByRole('button', { name: 'Alternar tema' }).click(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: `scratch/acesso-direto/primeiro-acesso-${info.project.name}.png` }) })
test('conta antiga mantém módulo; expiração/sessão obsoleta/erro falham fechados', async ({ page }) => { await simular(page, { sessao: true, estado: 'normal' }); await page.goto(`${pagina}?habilitado=1&modo=guard`); await expect(page.getByText('Módulo administrativo sintético')).toBeVisible() })
for (const estado of ['expirada', 'sessao_obsoleta', 'erro']) test(`guarda bloqueia ${estado} sem montar módulo`, async ({ page }) => { await simular(page, { sessao: true, estado }); await page.goto(`${pagina}?habilitado=1&modo=guard`); await expect(page.getByRole('button', { name: 'Sair', exact: true })).toBeVisible(); await expect(page.getByText('Módulo administrativo sintético')).toHaveCount(0); expect(await page.getAttribute('body', 'data-modulo-montado')).toBeNull() })
test('senha pessoal valida confirmação e falha do servidor preserva bloqueio', async ({ page }) => { const c = await simular(page, { sessao: true, estado: 'pendente', falha: 'SENHA_INVALIDA' }); await page.goto(`${pagina}?habilitado=1&modo=guard`); await page.getByLabel('Nova senha', { exact: true }).fill('SenhaSinteticaPessoal!426'); await page.getByLabel('Confirmar nova senha').fill('OutraSenhaSintetica!527'); await page.getByRole('button', { name: 'Salvar e continuar' }).click(); await expect(page.getByText('As senhas precisam ser iguais.')).toBeVisible(); expect(c.ativacoes).toBe(0); await page.getByLabel('Confirmar nova senha').fill('SenhaSinteticaPessoal!426'); await page.getByRole('button', { name: 'Salvar e continuar' }).click(); await expect(page.getByText(/A senha pessoal deve ser diferente da temporária/)).toBeVisible(); expect(c.ativacoes).toBe(1); expect(c.tokens).toBe(0) })
test('substituição exige confirmação e devolve segredo só após resposta', async ({ page }) => { const c = await simular(page); await page.goto(`${pagina}?habilitado=1&modo=substituir`); await page.getByRole('button', { name: 'Substituir credencial temporária' }).click(); expect(c.substituicoes).toBe(0); await page.getByRole('button', { name: 'Manter credencial' }).click(); expect(c.substituicoes).toBe(0); await page.getByRole('button', { name: 'Substituir credencial temporária' }).click(); await page.getByRole('button', { name: 'Substituir credencial', exact: true }).click(); await expect(page.getByRole('dialog', { name: 'Acesso preparado' })).toBeVisible(); expect(c.substituicoes).toBe(1) })
test('troca confirmada inicia sessão nova e limpa senha da interface', async ({ page }) => { const c = await simular(page); await page.goto(`${pagina}?habilitado=1&modo=senha`); await page.getByLabel('Nova senha', { exact: true }).fill('SenhaSinteticaPessoal!426'); await page.getByLabel('Confirmar nova senha').fill('SenhaSinteticaPessoal!426'); await page.getByRole('button', { name: 'Mostrar senhas' }).click(); await expect(page.getByLabel('Nova senha', { exact: true })).toHaveAttribute('type', 'text'); await page.getByRole('button', { name: 'Salvar e continuar' }).click(); await expect(page.getByText('Senha definida; sessão nova confirmada.')).toBeVisible(); expect(c.ativacoes).toBe(1); expect(c.tokens).toBe(1); expect(await page.evaluate(() => JSON.stringify({ ...localStorage }))).not.toContain('SenhaSinteticaPessoal') })
test('novo acesso usa tokens do tema escuro e cabe em 360px', async ({ page }, info) => { await simular(page); await page.setViewportSize({ width: 360, height: 800 }); await abrirNovo(page); await acesso(page); await page.evaluate(() => document.documentElement.dataset.theme = 'escuro'); await expect(page.getByRole('button', { name: 'Salvar pessoa e preparar acesso' })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); const d = page.getByRole('dialog', { name: 'Novo membro da equipe' }); expect(await d.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true); await page.screenshot({ path: `scratch/acesso-direto/novo-acesso-360-${info.project.name}.png` }) })
