import { test } from 'node:test'
import assert from 'node:assert/strict'
import { coordenarNovoMembro, validarNovoAcesso, validarSenhaPessoal } from '../../src/lib/acessoDiretoModelo.ts'
import { ativarDireto, compromissoSenha, gerarSenhaTemporaria, provisionarDireto, senhaPessoalValida, type ReservaDireta } from '../../supabase/functions/_shared/acessoDireto.ts'
import { exigirAtivacaoServico } from '../../supabase/functions/_shared/guardaAtivacao.ts'
import { exigirAtivacaoServidor } from '../../server/src/plugins/ativacao.ts'
const reserva = (): ReservaDireta => ({ id: crypto.randomUUID(), auth_user_id: crypto.randomUUID(), email: 'titular@example.invalid', salt: crypto.randomUUID(), estado: 'reservada', reserva_id: crypto.randomUUID(), expira_em: new Date(Date.now() + 86400000).toISOString(), revisao: 0 })
test('falha no desafio de senha pessoal impede revogação e conclusão', async () => { const r = reserva(); r.senha_digest = await compromissoSenha(r.salt, gerarSenhaTemporaria()); let revogadas = 0, confirmadas = 0; await assert.rejects(ativarDireto(gerarSenhaTemporaria(), { reservar: async () => r, atualizarSenha: async () => {}, verificarSenha: async () => { throw new Error('login recusado') }, revogarSessoes: async () => { revogadas++ }, confirmar: async () => { confirmadas++ } })); assert.equal(revogadas, 0); assert.equal(confirmadas, 0) })
test('confirmação final recusada não devolve estado ativa', async () => { const r = reserva(); r.senha_digest = await compromissoSenha(r.salt, gerarSenhaTemporaria()); const ordem: string[] = []; await assert.rejects(ativarDireto(gerarSenhaTemporaria(), { reservar: async () => r, atualizarSenha: async () => { ordem.push('auth') }, verificarSenha: async () => { ordem.push('verificar') }, revogarSessoes: async () => { ordem.push('revogar') }, confirmar: async () => { throw new Error('fingerprint divergente') } })); assert.deepEqual(ordem, ['auth','verificar','revogar']) })
test('API financeira nega pendência, shape inválido, ausência e falha de RPC', async () => { for (const data of [false,null,{},'true']) assert.equal(await exigirAtivacaoServidor({ rpc: async () => ({ data, error: null }) }),false); assert.equal(await exigirAtivacaoServidor({ rpc: async () => ({ data:true,error:{} }) }),false); await assert.rejects(exigirAtivacaoServidor({ rpc: async () => { throw new Error('indisponível') } })); assert.equal(await exigirAtivacaoServidor({ rpc: async () => ({ data:true,error:null }) }),true) })
test('cadastro sem acesso não invoca preparação', async () => { let chamadas = 0; const r = await coordenarNovoMembro({ salvarPessoa: async () => 'pessoa', prepararAcesso: async () => ++chamadas }, null, false); assert.equal(r.membroId, 'pessoa'); assert.equal(chamadas, 0) })
test('falha parcial devolve ID e retomada não duplica pessoa', async () => { let salvos = 0; const p = { salvarPessoa: async () => { salvos++; return 'pessoa' }, prepararAcesso: async () => { throw new Error('falha sintética') } }; await assert.rejects(coordenarNovoMembro(p, null, true), e => e instanceof Error && 'membroId' in e && e.membroId === 'pessoa'); await coordenarNovoMembro({ ...p, prepararAcesso: async () => 'pronto' }, 'pessoa', true); assert.equal(salvos, 1) })
test('falha de cadastro não inicia acesso', async () => { let acessos = 0; await assert.rejects(coordenarNovoMembro({ salvarPessoa: async () => { throw new Error('falha') }, prepararAcesso: async () => ++acessos }, null, true)); assert.equal(acessos, 0) })
test('e-mail de contato não substitui e-mail de login', () => assert.ok(validarNovoAcesso({ modo: 'temporaria', email: '', escopos: [{ clinica_id: 'A', papel: 'recepcao' }] }, ['A'])))
test('clínica sem papel, externa ou duplicada bloqueia conjunto', () => { for (const escopos of [[{ clinica_id: 'A', papel: '' }], [{ clinica_id: 'B', papel: 'recepcao' }], [{ clinica_id: 'A', papel: 'medico' }, { clinica_id: 'A', papel: 'recepcao' }]]) assert.ok(validarNovoAcesso({ modo: 'convite', email: 'a@example.invalid', escopos: escopos as never }, ['A'])) })
test('convite e temporária aceitam só escopo explícito válido', () => { for (const modo of ['convite', 'temporaria'] as const) assert.equal(validarNovoAcesso({ modo, email: ' a@example.invalid ', escopos: [{ clinica_id: 'A', papel: 'recepcao' }] }, ['A']), null) })
test('senhas individuais fortes, distintas e compromissos com salt', async () => { const senhas = new Set(Array.from({ length: 100 }, gerarSenhaTemporaria)); assert.equal(senhas.size, 100); for (const s of senhas) { assert.equal(s.length, 24); assert.ok(senhaPessoalValida(s)); assert.equal(validarSenhaPessoal(s, s), null) }; const s = [...senhas][0]; assert.notEqual(await compromissoSenha('a', s), await compromissoSenha('b', s)) })
test('requisitos e confirmação rejeitam valores inválidos', () => { for (const s of ['', '123456', 'A'.repeat(130), 'SenhaSemNumero!']) assert.ok(validarSenhaPessoal(s, s)); const s = gerarSenhaTemporaria(); assert.ok(validarSenhaPessoal(s, gerarSenhaTemporaria())) })
test('reserva antecede Auth e confirmação antecede entrega do segredo', async () => { const r = reserva(), ordem: string[] = []; const out = await provisionarDireto({ reservar: async () => { ordem.push('reserva'); return r }, buscarContaReservada: async () => { ordem.push('buscar'); return null }, criarConta: async () => { ordem.push('auth'); return { id: r.auth_user_id } }, confirmar: async (_r, digest) => { assert.match(digest, /^[a-f0-9]{64}$/); ordem.push('confirmar') } }); assert.deepEqual(ordem, ['reserva', 'buscar', 'auth', 'confirmar']); assert.ok(out.senhaTemporaria) })
test('falha de autorização/reserva nunca cria conta', async () => { let criadas = 0; await assert.rejects(provisionarDireto({ reservar: async () => { throw new Error('NAO_AUTORIZADO') }, buscarContaReservada: async () => null, criarConta: async () => { criadas++; return { id: '' } }, confirmar: async () => {} })); assert.equal(criadas, 0) })
test('e-mail já existente na reserva não cria nem redefine', async () => { let criadas = 0; await assert.rejects(provisionarDireto({ reservar: async () => { throw new Error('CONTA_EXISTENTE') }, buscarContaReservada: async () => null, criarConta: async () => { criadas++; return { id: '' } }, confirmar: async () => {} })); assert.equal(criadas, 0) })
test('repetição de operação confirmada não cria nem revela senha', async () => { const r = { ...reserva(), estado: 'pendente' }; let criadas = 0; const o = await provisionarDireto({ reservar: async () => r, buscarContaReservada: async () => null, criarConta: async () => { criadas++; return { id: '' } }, confirmar: async () => {} }); assert.equal(o.senhaTemporaria, null); assert.equal(criadas, 0) })
test('recuperação usa ID reservado e metadata do servidor; segredo perdido exige substituição', async () => { const r = reserva(); let criadas = 0, compromisso = 'não confirmado'; const o = await provisionarDireto({ reservar: async () => r, buscarContaReservada: async () => ({ id: r.auth_user_id, email: r.email, operacao: r.id }), criarConta: async () => { criadas++; return { id: '' } }, confirmar: async (_r, d) => { compromisso = d } }); assert.equal(criadas, 0); assert.equal(o.senhaTemporaria, null); assert.equal(compromisso, '') })
test('coincidência de e-mail sem operação reservada não vincula', async () => { const r = reserva(); let confirmadas = 0; await assert.rejects(provisionarDireto({ reservar: async () => r, buscarContaReservada: async () => ({ id: r.auth_user_id, email: r.email, operacao: 'outra' }), criarConta: async () => ({ id: '' }), confirmar: async () => { confirmadas++ } })); assert.equal(confirmadas, 0) })
test('resposta Auth com outro ID nunca confirma', async () => { const r = reserva(); let confirmadas = 0; await assert.rejects(provisionarDireto({ reservar: async () => r, buscarContaReservada: async () => null, criarConta: async () => ({ id: 'outro' }), confirmar: async () => { confirmadas++ } })); assert.equal(confirmadas, 0) })
test('falha depois do Auth não entrega senha nem declara sucesso', async () => { const r = reserva(); await assert.rejects(provisionarDireto({ reservar: async () => r, buscarContaReservada: async () => null, criarConta: async () => ({ id: r.auth_user_id }), confirmar: async () => { throw new Error('falha') } })) })
test('senha pessoal igual à temporária não altera Auth', async () => { const r = reserva(), s = gerarSenhaTemporaria(); r.senha_digest = await compromissoSenha(r.salt, s); let chamadas = 0; await assert.rejects(ativarDireto(s, { reservar: async () => r, atualizarSenha: async () => { chamadas++ }, verificarSenha: async () => {}, revogarSessoes: async () => {}, confirmar: async () => {} })); assert.equal(chamadas, 0) })
test('compromisso perdido não permite ativação', async () => { const r = reserva(); let chamadas = 0; await assert.rejects(ativarDireto(gerarSenhaTemporaria(), { reservar: async () => r, atualizarSenha: async () => { chamadas++ }, verificarSenha: async () => {}, revogarSessoes: async () => {}, confirmar: async () => {} })); assert.equal(chamadas, 0) })
test('servidor verifica login pessoal e revoga antes de confirmar ativação', async () => { const r = reserva(); r.senha_digest = await compromissoSenha(r.salt, gerarSenhaTemporaria()); const ordem: string[] = []; const out = await ativarDireto(gerarSenhaTemporaria(), { reservar: async () => r, atualizarSenha: async () => { ordem.push('auth') }, verificarSenha: async () => { ordem.push("verificar") }, revogarSessoes: async () => { ordem.push('revogar') }, confirmar: async () => { ordem.push('confirmar') } }); assert.deepEqual(ordem, ['auth', 'verificar', 'revogar', 'confirmar']); assert.equal(out.estado, 'ativa') })
test('falha no Auth ou revogação não marca conta ativa', async () => { for (const falha of ['auth', 'revogar']) { const r = reserva(); r.senha_digest = await compromissoSenha(r.salt, gerarSenhaTemporaria()); let confirmadas = 0; await assert.rejects(ativarDireto(gerarSenhaTemporaria(), { reservar: async () => r, atualizarSenha: async () => { if (falha === 'auth') throw new Error('falha') }, verificarSenha: async () => {}, revogarSessoes: async () => { if (falha === 'revogar') throw new Error('falha') }, confirmar: async () => { confirmadas++ } })); assert.equal(confirmadas, 0) } })
test('expiração ou sessão antiga recusada pelo banco impede chamada Auth', async () => { for (const causa of ['CREDENCIAL_EXPIRADA', 'CONFLITO']) { let atualizadas = 0; await assert.rejects(ativarDireto(gerarSenhaTemporaria(), { reservar: async () => { throw new Error(causa) }, atualizarSenha: async () => { atualizadas++ }, verificarSenha: async () => {}, revogarSessoes: async () => {}, confirmar: async () => {} })); assert.equal(atualizadas, 0) } })
test('serviços com gate recusam erro, ausência, false e shape inválido', async () => { for (const r of [{ data: false, error: null }, { data: null, error: {} }, { data: {}, error: null }]) await assert.rejects(exigirAtivacaoServico({ rpc: async () => r })); await exigirAtivacaoServico({ rpc: async () => ({ data: true, error: null }) }) })
