import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react'
import { Tabs } from '@base-ui/react/tabs'
import { Building2, Palette, FileText, LogIn, History, Settings, Eye, Download } from 'lucide-react'
import { FeedbackAlert } from '../components/feedback/FeedbackAlert'
import { ConfirmacaoDialog } from '../components/feedback/ConfirmacaoDialog'
import { Collapsible,CollapsibleTrigger,CollapsiblePanel } from '../components/ui/collapsible'
import { PreviaTimbradoAutomatica } from '../components/configuracoes/PreviaTimbrado'
import { consultarCep, formatarCep, formatarTelefoneBrasil } from '../lib/pacienteFormulario'
import { ATIVOS, PADRAO, VARIAVEIS, TIPOS_DOCUMENTO, resolverTipoDocumento, voltarAoPadrao, instituicaoVazia, validarDocumento, validarImagemInstitucional, criarSnapshot, ErroConfiguracao, servicoConfiguracoes, type ServicoConfiguracoes, type ConsultaConfiguracao, type DocumentoConfiguracao, type Apresentacao, type CampoInstituicao, type Linha, type TipoDocumento, type Variavel } from '../lib/configuracoes'
import './configuracoes.css'
export interface GuardaConfiguracoes { sujo: boolean; ocupado: boolean; salvar: () => Promise<boolean> }
const SECOES=[['dados','Dados da clínica',Building2],['identidade','Identidade visual',Palette],['timbrados','Timbrados e documentos',FileText],['login','Tela de login',LogIn],['historico','Histórico de alterações',History]] as const
const ROTULOS_TIPO: Record<TipoDocumento,string>={padrao:'Padrão da unidade',relatorio_financeiro:'Relatório financeiro',receita:'Receita — emissor futuro',declaracao:'Declaração — emissor futuro',atestado:'Atestado — emissor futuro',solicitacao_exames:'Solicitação de exames — emissor futuro'}
const LABELS: Record<CampoInstituicao,string>={nome:'Nome da unidade',nomeFantasia:'Nome fantasia',nomeExibicao:'Nome de exibição',razaoSocial:'Razão social',cnpj:'CNPJ',cep:'CEP',logradouro:'Logradouro',numero:'Número',complemento:'Complemento',bairro:'Bairro',cidade:'Cidade',uf:'UF',telefone:'Telefone',whatsapp:'WhatsApp',email:'E-mail institucional',site:'Site',empresaId:'Instituição emissora'}
export default function Configuracoes({clinicaId,clinicaNome,papel,onGuarda,onEquipe,servico=servicoConfiguracoes}: {clinicaId:string;clinicaNome:string;papel:string;onGuarda?:(g:GuardaConfiguracoes|null)=>void;onEquipe?:()=>void;servico?:ServicoConfiguracoes}) {
  const [consulta,setConsulta]=useState<ConsultaConfiguracao|null>(null),[documento,setDocumento]=useState<DocumentoConfiguracao|null>(null)
  const [secao,setSecao]=useState('dados'),[escopo,setEscopo]=useState(clinicaId),[tipo,setTipo]=useState<TipoDocumento>('padrao')
  const [carregando,setCarregando]=useState(true),[ocupado,setOcupado]=useState(false),[erro,setErro]=useState(''),[conferir,setConferir]=useState(false),[sucesso,setSucesso]=useState(''),[cepAviso,setCepAviso]=useState('')
  const [pdf,setPdf]=useState(''),[ativos,setAtivos]=useState<Record<string,string>>({}),[pdfOcupado,setPdfOcupado]=useState(false),[confirmar,setConfirmar]=useState<'aplicar'|'fonte'|number|null>(null)
  const [mudancaEscopo,setMudancaEscopo]=useState<string|null>(null)
  const base=useRef(''),urlLocais=useRef<string[]>([]),vivo=useRef(true),ultimaEdicao=useRef(0),consultaToken=useRef(0)
  const tipoAtual=useRef(tipo);tipoAtual.current=tipo
  const sujo=!!documento && JSON.stringify(documento)!==base.current
  const permitido=papel==='proprietaria'
  const carregar=useCallback(async (alvo=escopo) => {
    const token=++consultaToken.current;ultimaEdicao.current++
    setCarregando(true);setErro('');setSucesso('')
    try {const c=await servico.consultar(alvo);if(!vivo.current||token!==consultaToken.current)return;setConsulta(c);setDocumento(structuredClone(c.documento));setAtivos(c.ativos);base.current=JSON.stringify(c.documento);setConferir(false)}
    catch(e){if(vivo.current&&token===consultaToken.current){setConsulta(null);setDocumento(null);setErro(e instanceof Error?e.message:'Consulta indisponível.')}}finally{if(vivo.current&&token===consultaToken.current)setCarregando(false)}
  },[escopo,servico])
  const invalidarConsultas=useCallback(()=>{consultaToken.current++;ultimaEdicao.current++},[])
  useEffect(()=>{const urls=urlLocais.current;vivo.current=true;if(permitido)void carregar();return()=>{vivo.current=false;invalidarConsultas();urls.forEach(URL.revokeObjectURL);urls.length=0}},[carregar,permitido,invalidarConsultas])
  useEffect(()=>{if(!sujo)return;const h=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',h);return()=>window.removeEventListener('beforeunload',h)},[sujo])
  useEffect(()=>{setPdf('')},[documento,tipo,ativos])
  useEffect(()=>()=>{if(pdf)URL.revokeObjectURL(pdf)},[pdf])
  function editar(d:DocumentoConfiguracao){ultimaEdicao.current++;setDocumento(d);setSucesso('')}
  function alterarInstituicao(k:CampoInstituicao,v:string){if(documento?.instituicao)editar({...documento,instituicao:{...documento.instituicao,[k]:v}})}
  const campos=documento?(tipo==='padrao'?documento.campos:documento.variacoes[tipo] ?? {}):{}
  const efetivo=documento?resolverTipoDocumento(escopo==='geral'?{}:consulta?.geral??{},escopo==='geral'?{}:consulta?.geralVariacoes??{},documento.campos,documento.variacoes,tipo):PADRAO
  function alterarCampo(k:keyof Apresentacao,v:unknown,herdar=false){if(!documento)return;const novo=herdar?voltarAoPadrao(campos,k):{...campos,[k]:v};editar(tipo==='padrao'?{...documento,campos:novo}:{...documento,variacoes:{...documento.variacoes,[tipo]:novo}})}
  const salvar=useCallback(async (aplicar:boolean,atualizarFonte=false):Promise<boolean> => {
    if(!documento||!consulta||!consulta.disponivel||conferir){setErro('Salvamento indisponível. Reconsulte ou aguarde ativação do backend.');return false}
    if(consulta.fonteConflitante&&!atualizarFonte){setErro('Atualize os dados oficiais no rascunho antes de salvar ou aplicar.');return false}
    if(atualizarFonte&&!consulta.instituicaoAtual){setErro('Dados oficiais indisponíveis. Reconsulte.');return false}
    setOcupado(true);setErro('');setSucesso('')
    try {const d=atualizarFonte?{...documento,instituicao:consulta.instituicaoAtual}:documento;const c=await servico.salvar(escopo,validarDocumento(d,escopo==='geral'),consulta.revisao,consulta.geralRevisao,aplicar,consulta.fonteRevisao);if(!vivo.current)return false
      setConsulta(c);setDocumento(c.documento);base.current=JSON.stringify(c.documento);setAtivos(c.ativos);setSucesso(aplicar?'Configuração aplicada e confirmada pelo servidor.':'Rascunho salvo e confirmado pelo servidor. A apresentação em uso permanece a versão aplicada.');if(aplicar)window.dispatchEvent(new Event('clinica:configuracao-aplicada'));return true
    }catch(e){setErro(e instanceof Error?e.message:'Salvamento não confirmado.');if(e instanceof ErroConfiguracao&&(e.conferir||e.status===409))setConferir(true);return false}finally{if(vivo.current)setOcupado(false)}
  },[documento,consulta,conferir,servico,escopo])
  useEffect(()=>{onGuarda?.({sujo,ocupado,salvar:()=>salvar(false)});return()=>onGuarda?.(null)},[onGuarda,sujo,ocupado,salvar])
  async function restaurar(versao:number){if(!consulta)return;setOcupado(true);setErro('');try{const c=await servico.restaurar(escopo,versao,consulta.revisao,consulta.geralRevisao,consulta.fonteRevisao);setConsulta(c);setDocumento(c.documento);base.current=JSON.stringify(c.documento);setAtivos(c.ativos);setSucesso('Versão restaurada como novo rascunho no histórico. Confira os dados antes de aplicar.')}catch(e){setErro(e instanceof Error?e.message:'Restauração não confirmada.');setConferir(true)}finally{setOcupado(false)}}
  async function buscarCep(){
    const atual=documento?.instituicao;if(!atual)return;const edicao=ultimaEdicao.current,token=consultaToken.current;setCepAviso('Consultando CEP…')
    try{const e=await consultarCep(atual.cep);if(!vivo.current||token!==consultaToken.current)return;if(edicao!==ultimaEdicao.current)return setCepAviso('O formulário mudou. Consulte novamente para preservar sua edição.')
      if(!e)return setCepAviso('CEP não encontrado. Preencha o endereço manualmente.')
      editar({...documento!,instituicao:{...atual,logradouro:e.logradouro||atual.logradouro,bairro:e.bairro||atual.bairro,cidade:e.cidade||atual.cidade,uf:e.uf||atual.uf}});setCepAviso('Endereço sugerido pelo CEP. Confira e corrija os campos se necessário.')
    }catch{if(vivo.current&&token===consultaToken.current)setCepAviso('Consulta indisponível. Você pode preencher o endereço manualmente.')}
  }
  async function arquivo(k:typeof ATIVOS[number],file?:File){if(!file)return;setOcupado(true);setErro('');try{await validarImagemInstitucional(file);if(consulta?.disponivel){const a=await servico.enviar(escopo,file);setAtivos(v=>({...v,[a.caminho]:a.url}));alterarCampo(k,a.caminho)}else{const path=`${escopo}/${crypto.randomUUID()}.${file.type==='image/png'?'png':'jpg'}`,url=URL.createObjectURL(file);urlLocais.current.push(url);setAtivos(v=>({...v,[path]:url}));alterarCampo(k,path)}}catch(e){setErro(e instanceof Error?e.message:'Use uma imagem JPEG ou PNG válida, até 5 MB.')}finally{setOcupado(false)}}
  const ficticia={...instituicaoVazia(),nome:'Unidade de demonstração',nomeExibicao:'Clínica Exemplo',razaoSocial:'Instituição fictícia para demonstração',cnpj:'11.222.333/0001-81',logradouro:'Avenida de Demonstração das Instituições Multiclínicas e Serviços Integrados',numero:'100',complemento:'Bloco de Exemplo, sala demonstrativa 101',bairro:'Centro',cidade:'Cidade de Exemplo',uf:'BA',telefone:'(71) 00000-0000',email:'contato@example.invalid',site:'https://example.invalid'}
  const snapshotPrevia=criarSnapshot(escopo,consulta?.revisao??0,tipo,ficticia,efetivo,ativos)
  async function previa(){const token=consultaToken.current,edicao=ultimaEdicao.current,tipoGerado=tipo;setPdfOcupado(true);setErro('');try{
    const {CONTEUDO_DEMONSTRACAO,gerarPdfTimbrado}=await import('../lib/timbradoPdf')
    const blob=await gerarPdfTimbrado(snapshotPrevia,CONTEUDO_DEMONSTRACAO,true);if(vivo.current&&token===consultaToken.current&&edicao===ultimaEdicao.current&&tipoGerado===tipoAtual.current)setPdf(URL.createObjectURL(blob))
  }catch(e){if(vivo.current&&token===consultaToken.current)setErro(e instanceof Error?e.message:'Prévia indisponível.')}finally{if(vivo.current)setPdfOcupado(false)}}
  function campo(k:keyof Apresentacao,label:string,controle:(valor:Apresentacao[typeof k],alterar:(v:unknown)=>void)=>ReactNode){const herdado=!Object.hasOwn(campos,k);return <div className="cfg-campo"><div className="cfg-campo-topo"><span>{label}</span>{escopo!=='geral'&&<span className="cfg-heranca">{herdado?(tipo==='padrao'?'Padrão geral':'Padrão da unidade'):'Personalizado'}</span>}</div>{controle(efetivo[k],v=>alterarCampo(k,v))}{escopo!=='geral'&&<button type="button" className="cfg-link" disabled={ocupado} onClick={()=>alterarCampo(k,efetivo[k],!herdado)}>{herdado?'Personalizar nesta unidade':'Voltar ao padrão'}</button>}</div>}
  const texto=(k:keyof Apresentacao,label:string,max=180)=>campo(k,label,(v,c)=><input aria-label={label} value={String(v)} maxLength={max} onChange={e=>c(e.target.value)} />)
  const numero=(k:keyof Apresentacao,label:string,min:number,max:number)=>campo(k,label,(v,c)=><input aria-label={label} type="number" min={min} max={max} value={Number(v)} onChange={e=>c(Number(e.target.value))}/>)
  const opcoes=(k:keyof Apresentacao,label:string,opts:[string,string][])=>campo(k,label,(v,c)=><select aria-label={label} value={String(v)} onChange={e=>c(e.target.value)}>{opts.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>)
  const flag=(k:keyof Apresentacao,label:string)=>campo(k,label,(v,c)=><label className="cfg-check"><input type="checkbox" checked={Boolean(v)} onChange={e=>c(e.target.checked)} />Exibir</label>)
  function ativo(k:typeof ATIVOS[number],label:string){return campo(k,label,(v,c)=><><div className="cfg-imagem"><ImagemInstitucional url={ativos[String(v)]} label={label}/></div><label className="cfg-link cfg-upload">Selecionar PNG ou JPEG<input type="file" accept="image/png,image/jpeg" aria-label={`Selecionar ${label}`} disabled={ocupado} onChange={e=>{void arquivo(k,e.target.files?.[0]);e.target.value=''}}/></label>{!!v&&<button type="button" className="cfg-link" onClick={()=>c('')}>Remover desta configuração</button>}</>)}
  if(!permitido)return <FeedbackAlert variant="destructive" title="Página não autorizada" description="Configurações exige Proprietário(a) autorizado na unidade." />
  return <div className="cfg-pagina">
    <header className="cfg-titulo"><div><p className="cfg-kicker"><Settings size={15} aria-hidden/>Administração institucional</p><h1>Configurações</h1><p>Dados, apresentação e documentos no contexto da unidade.</p></div><label className="cfg-escopo">Alcance da edição<select aria-label="Alcance da edição" value={escopo} disabled={ocupado} onChange={e=>sujo?setMudancaEscopo(e.target.value):setEscopo(e.target.value)}><option value={clinicaId}>{clinicaNome}</option><option value="geral" disabled={!consulta?.podeGeral}>Padrão geral do Sistema Multiclínicas</option></select></label></header>
    <div className="cfg-contexto"><strong>{escopo==='geral'?'Padrão geral — somente apresentação':clinicaNome}</strong><span>{escopo==='geral'?'Afeta as unidades que usam herança.':'Alterações restritas a esta unidade. Dados jurídicos não são herdados.'}</span></div>
    {erro&&<FeedbackAlert variant="destructive" title="Operação não concluída" description={erro} />}{sucesso&&<FeedbackAlert variant="success" title="Operação confirmada" description={sucesso} onClose={()=>setSucesso('')}/>}
    {carregando?<div className="cfg-skeleton" role="status">Consultando configurações oficiais…</div>:!consulta||!documento?<button className="cfg-botao" onClick={()=>void carregar()}>Tentar consultar novamente</button>:<>
    {!consulta.disponivel&&<FeedbackAlert variant="warning" title="Edição e prévia locais" description="Alterações não serão salvas. Salvar, aplicar e enviar imagens aguardam ativação." />}
    {consulta.fonteConflitante&&<FeedbackAlert variant="warning" title="Os dados oficiais mudaram" description="O rascunho contém dados anteriores. Atualize-os antes de salvar ou aplicar." action={<button className="cfg-link" disabled={ocupado||conferir||!consulta.disponivel} onClick={()=>setConfirmar('fonte')}>Atualizar dados oficiais no rascunho</button>}/>}
    <Collapsible className="cfg-ajuda-recolhivel"><CollapsibleTrigger>Ajuda e integrações</CollapsibleTrigger><CollapsiblePanel><p className="cfg-ajuda">{!consulta.disponivel?'O serviço de Configurações ainda não foi aplicado. Imagens selecionadas ficam apenas nesta sessão; campos novos, empresas vinculadas e histórico ainda não podem ser consultados.':''}</p>{!consulta.podeGeral&&<p className="cfg-ajuda">Editar o padrão geral exige autorização específica. Administrar uma unidade não concede esse acesso.</p>}<p className="cfg-ajuda">A prévia usa dados fictícios e acompanha a apresentação em edição. O PDF completo só é gerado pelo botão. O relatório financeiro por clínica aguarda ativação; emissores clínicos serão integrados futuramente.</p><p className="cfg-ajuda">Empresa emissora mantém razão social e CNPJ no cadastro oficial da Equipe. Endereço jurídico ainda sem fonte oficial própria não é substituído pelo endereço da unidade. Imagens e versões anteriores são preservadas.</p><p className="cfg-ajuda">Nome e cidade são obrigatórios. Informações ausentes não são inventadas; cada emissor deverá exigir seus dados necessários.</p></CollapsiblePanel></Collapsible>
    <button type="button" className="cfg-link cfg-atalho-previa" onClick={()=>document.getElementById('cfg-previa')?.scrollIntoView({block:'start'})}>Ir à prévia</button>
    <Tabs.Root value={secao} onValueChange={v=>{setSecao(String(v));setTipo('padrao')}}>
      <Tabs.List className="cfg-abas" aria-label="Seções de configurações">{SECOES.map(([k,l,Icon])=><Tabs.Tab key={k} value={k}><Icon size={17} aria-hidden/>{l}</Tabs.Tab>)}</Tabs.List>
      <div className="cfg-workspace"><div className="cfg-editor"><fieldset disabled={ocupado}>
      <Tabs.Panel value="dados"><h2>Dados oficiais da unidade</h2><p className="cfg-ajuda">Nome e cidade são obrigatórios. Complete os demais campos quando disponíveis.</p>{escopo==='geral'?<p>Dados jurídicos e endereço pertencem a cada instituição.</p>:<>
      <label className="cfg-campo">Instituição emissora<select aria-label="Instituição emissora" value={documento.instituicao?.empresaId??''} onChange={e=>alterarInstituicao('empresaId',e.target.value)}><option value="">A própria unidade, conforme seu cadastro oficial</option>{!!documento.instituicao?.empresaId&&!consulta.empresas.some(e=>e.id===documento.instituicao?.empresaId)&&<option value={documento.instituicao.empresaId}>Instituição já vinculada — cadastro oficial</option>}{consulta.empresas.map(e=><option key={e.id} value={e.id}>{e.nome} · {e.unidades>1?'compartilhada entre unidades':'cadastro da unidade'}</option>)}</select></label>
      {!!documento.instituicao?.empresaId&&<div className="cfg-ajuda">Razão social e CNPJ vêm da empresa escolhida. A edição compartilhada continua no cadastro oficial da Equipe. {onEquipe&&<button type="button" className="cfg-link" onClick={onEquipe}>Abrir Equipe</button>}</div>}
      <div className="cfg-grid">{Object.entries(LABELS).filter(([k])=>k!=='empresaId').map(([k,label])=>{const key=k as CampoInstituicao,empresa=consulta.empresas.find(e=>e.id===documento.instituicao?.empresaId);const compartilhado=!!documento.instituicao?.empresaId&&['cnpj','razaoSocial'].includes(k);const value=compartilhado?(key==='cnpj'?empresa?.cnpj??documento.instituicao?.cnpj:empresa?.nome??documento.instituicao?.razaoSocial):documento.instituicao?.[key]??'';return <label className="cfg-campo" key={k}>{label}<input aria-label={label} readOnly={compartilhado} required={['nome','cidade'].includes(k)} maxLength={240} inputMode={['cep','telefone','whatsapp'].includes(k)?'numeric':k==='email'?'email':undefined} value={value} onChange={e=>{let v=e.target.value;if(k==='cep')v=formatarCep(v);if(k==='telefone'||k==='whatsapp')v=formatarTelefoneBrasil(v);if(k==='uf')v=v.toUpperCase().slice(0,2);if(k==='cnpj')v=v.replace(/[^a-z\d]/gi,'').toUpperCase().slice(0,14).replace(/^(.{2})(.{3})(.{3})(.{4})(.{0,2})$/,'$1.$2.$3/$4-$5');alterarInstituicao(key,v)}}/>{k==='cep'&&<button type="button" className="cfg-link" onClick={()=>void buscarCep()}>Consultar CEP</button>}</label>})}</div>{cepAviso&&<p role="status" className="cfg-ajuda">{cepAviso}</p>}
      <p className="cfg-ajuda">Confira os dados da instituição antes de aplicar.</p>
      </>}</Tabs.Panel>
      <Tabs.Panel value="identidade"><h2>Identidade visual</h2><p className="cfg-ajuda">PNG ou JPEG, até 5 MB. De 32 a 4096 px e até 8 megapixels.</p><div className="cfg-grid">{ativo('logoPrincipal','Logo principal')}{ativo('logoImpressao','Logo para impressão')}{ativo('logoCompacta','Logo compacta')}{ativo('favicon','Ícone da aba')}</div>{texto('cor','Cor institucional',7)}<p className="cfg-ajuda">Use #RRGGBB com contraste de 4,5:1 com branco. Foto pessoal: Meu perfil.</p></Tabs.Panel>
      <Tabs.Panel value="timbrados"><h2>Timbrados e documentos</h2><label className="cfg-campo">Modelo de apresentação<select aria-label="Modelo de apresentação" value={tipo} onChange={e=>setTipo(e.target.value as TipoDocumento)}>{TIPOS_DOCUMENTO.map(t=><option value={t} key={t}>{ROTULOS_TIPO[t]}</option>)}</select></label><p className="cfg-ajuda">Configure a apresentação. Modelos clínicos ainda não emitem documentos.</p><div className="cfg-grid">{opcoes('logoPosicao','Posição da logo',[['left','Esquerda'],['center','Centro'],['right','Direita']])}{numero('logoLargura','Largura máxima da logo (mm)',12,50)}{opcoes('alinhamento','Alinhamento do texto',[['left','Esquerda'],['center','Centro'],['right','Direita']])}{numero('margem','Margens (mm)',12,28)}{numero('espaco','Espaçamento (mm)',2,8)}{flag('nomeInstitucional','Nome institucional')}{flag('paginas','Numeração de páginas')}</div>
      {campo('cabecalho','Campos do cabeçalho',(v,c)=><EditorLinhas linhas={v as Linha[]} onChange={c} label="Cabeçalho"/>)}{campo('rodape','Campos do rodapé',(v,c)=><EditorLinhas linhas={v as Linha[]} onChange={c} label="Rodapé"/>)}{texto('marcaDagua','Marca-d’água opcional',60)}<p className="cfg-ajuda">Cabeçalho e rodapé se repetem em cada página. A prévia mede a área útil e recusa composição excessiva.</p></Tabs.Panel>
      <Tabs.Panel value="login"><h2>Tela de login</h2><p className="cfg-ajuda">Identidade pública conforme o domínio autorizado. Não concede acesso à unidade e não publica rascunhos.</p><div className="cfg-grid">{ativo('loginLogo','Logo do login')}{ativo('loginImagem','Imagem institucional')}</div>{texto('loginMensagem','Mensagem de boas-vindas')}<div className="cfg-grid">{numero('loginFocoX','Ponto focal horizontal (%)',0,100)}{numero('loginFocoY','Ponto focal vertical (%)',0,100)}{opcoes('loginDesktop','Composição no computador',[['lateral','Imagem lateral'],['compacto','Imagem compacta']])}{opcoes('loginMobile','Composição no celular',[['compacto','Imagem compacta'],['semImagem','Somente formulário']])}</div><p className="cfg-ajuda">Brotas: clinicabrotas.com.br · Ipupiara: clinicaipupiara.com.br. Falhas nas imagens ou configuração preservam o formulário.</p></Tabs.Panel>
      <Tabs.Panel value="historico"><h2>Histórico de alterações</h2><p className="cfg-ajuda">Restaurar cria um novo rascunho e preserva as versões anteriores.</p>{consulta.historico.length?<ol className="cfg-historico">{consulta.historico.map(v=><li key={v.revisao}><strong>Versão {v.revisao} · {v.acao}</strong><p>{v.autor} · {new Date(v.instante).toLocaleString('pt-BR',{timeZone:'America/Bahia'})}</p><button className="cfg-link" disabled={sujo||conferir||consulta.fonteConflitante} onClick={()=>setConfirmar(v.revisao)}>Restaurar como rascunho</button></li>)}</ol>:<p>Nenhuma versão persistente consultada. O histórico estará disponível após a ativação e o primeiro salvamento.</p>}</Tabs.Panel>
      </fieldset></div><aside id="cfg-previa" className="cfg-previa" aria-label="Prévia da configuração"><div className="cfg-previa-titulo"><h2><Eye size={18} aria-hidden/>Prévia</h2><span>Dados fictícios</span></div>{secao==='login'?<div className="cfg-login-preview" data-mobile={efetivo.loginMobile} data-desktop={efetivo.loginDesktop}>{efetivo.loginImagem&&ativos[efetivo.loginImagem]&&<img src={ativos[efetivo.loginImagem]} alt="Imagem institucional demonstrativa" style={{objectPosition:`${efetivo.loginFocoX}% ${efetivo.loginFocoY}%`}}/>}<div>{efetivo.loginLogo&&ativos[efetivo.loginLogo]&&<img className="cfg-login-logo" src={ativos[efetivo.loginLogo]} alt="Logo demonstrativa"/>}<strong>{efetivo.loginMensagem||'Bem-vindo à clínica'}</strong><p>Formulário de acesso preservado</p><div className="cfg-input-ficticio">E-mail cadastrado</div><div className="cfg-input-ficticio">Senha</div><span className="cfg-entrar-ficticio">Entrar</span></div></div>:<><PreviaTimbradoAutomatica snapshot={snapshotPrevia}/><button className="cfg-botao" disabled={pdfOcupado||ocupado} onClick={()=>void previa()}>{pdfOcupado?'Gerando PDF…':'Gerar PDF de demonstração'}</button>{pdf&&<><a className="cfg-link" href={pdf} download="demonstracao-timbrado.pdf"><Download size={15} aria-hidden/>Baixar PDF de demonstração</a><Collapsible><CollapsibleTrigger>Conferir PDF gerado</CollapsibleTrigger><CollapsiblePanel><object data={pdf} type="application/pdf" aria-label="PDF demonstrativo A4"><p>Use Baixar PDF de demonstração para abrir o arquivo.</p></object></CollapsiblePanel></Collapsible></>}</>}<p className="cfg-ajuda">Demonstração sem validade clínica. Nada é salvo ao visualizar.</p></aside></div>
    </Tabs.Root>
    <footer className="cfg-acoes"><p role="status">{sujo?'Alterações não salvas':`Versão consultada: ${consulta.revisao} · ${escopo==='geral'?'Sistema Multiclínicas':clinicaNome}`}</p><div><button className="cfg-botao" disabled={ocupado||!sujo} onClick={()=>{setDocumento(structuredClone(consulta.documento));setErro('');setSucesso('')}}>Cancelar edição</button><button className="cfg-botao" disabled={ocupado||!consulta.disponivel||conferir||consulta.fonteConflitante||!sujo} onClick={()=>void salvar(false)}>Salvar rascunho</button><button className="cfg-botao cfg-primario" disabled={ocupado||!consulta.disponivel||conferir||consulta.fonteConflitante} onClick={()=>setConfirmar('aplicar')}>Aplicar configuração</button></div>{conferir&&<button className="cfg-link" onClick={()=>setMudancaEscopo(escopo)}>Reconsultar estado no servidor</button>}</footer>
    </>}
    <ConfirmacaoDialog open={confirmar!==null} onOpenChange={o=>{if(!o)setConfirmar(null)}} tone="warning" title={confirmar==='fonte'?'Atualizar dados oficiais no rascunho?':confirmar==='aplicar'?'Aplicar configuração institucional?':'Restaurar versão como novo rascunho?'} description={confirmar==='fonte'?'Os dados da instituição neste rascunho serão substituídos pelo cadastro oficial atual. A apresentação e as imagens em edição serão mantidas. Será salvo um novo rascunho, sem aplicar.':confirmar==='aplicar'?`A apresentação e os dados oficiais de ${escopo==='geral'?'todas as unidades que usam herança':clinicaNome} serão atualizados. Documentos antigos permanecem preservados.`:'A versão anterior será copiada para um novo rascunho. Confira dados jurídicos e imagens antes de aplicar.'} confirmLabel={confirmar==='fonte'?'Atualizar rascunho':confirmar==='aplicar'?'Aplicar configuração':'Restaurar rascunho'} disabled={ocupado} onConfirm={()=>{const c=confirmar;setConfirmar(null);if(c==='fonte')void salvar(false,true);else if(c==='aplicar')void salvar(true);else if(typeof c==='number')void restaurar(c)}}/>
    <ConfirmacaoDialog disabled={ocupado} open={mudancaEscopo!==null} onOpenChange={o=>{if(!o)setMudancaEscopo(null)}} tone="warning" title="Conferir alterações pendentes" description="Para reconsultar ou mudar o alcance, salve o rascunho ou descarte a edição local." confirmLabel="Descartar e continuar" cancelLabel="Continuar editando" onConfirm={()=>{const alvo=mudancaEscopo;setMudancaEscopo(null);if(alvo===escopo)void carregar();else if(alvo)setEscopo(alvo)}}><button className="cfg-botao" disabled={!consulta?.disponivel||conferir||ocupado} onClick={()=>void salvar(false).then(ok=>{if(ok&&mudancaEscopo){const alvo=mudancaEscopo;setMudancaEscopo(null);if(alvo===escopo)void carregar();else setEscopo(alvo)}})}>Salvar rascunho e continuar</button></ConfirmacaoDialog>
  </div>
}
function EditorLinhas({linhas,onChange,label}: {linhas:Linha[];onChange:(v:Linha[])=>void;label:string}) {
  const adicionar=(n:number,p:Linha[number])=>onChange(linhas.map((l,i)=>i===n?[...l,p]:l))
  return <div className="cfg-linhas">{linhas.map((l,n)=><div key={n}><p>Linha {n+1}</p><div className="cfg-chips">{l.map((p,j)=><span key={j}>{'campo'in p?VARIAVEIS[p.campo]:p.texto}<button type="button" aria-label={`Remover item ${j+1} da linha ${n+1} do ${label}`} onClick={()=>onChange(linhas.map((linha,i)=>i===n?linha.filter((_,q)=>q!==j):linha))}>×</button></span>)}</div><select aria-label={`Adicionar campo à linha ${n+1} do ${label}`} value="" disabled={l.length>=8} onChange={e=>{if(e.target.value)adicionar(n,{campo:e.target.value as Variavel})}}><option value="">Escolher campo institucional…</option>{Object.entries(VARIAVEIS).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><input aria-label={`Texto complementar da linha ${n+1} do ${label}`} placeholder="Texto simples: Enter para adicionar" maxLength={120} disabled={l.length>=8} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();const v=e.currentTarget.value.trim();if(v){adicionar(n,{texto:v});e.currentTarget.value=''}}}}/><button className="cfg-link" type="button" onClick={()=>onChange(linhas.filter((_,i)=>i!==n))}>Remover linha</button></div>)}<button className="cfg-link" type="button" disabled={linhas.length>=3} onClick={()=>onChange([...linhas,[]])}>Adicionar linha</button></div>
}


function ImagemInstitucional({url,label}:{url?:string;label:string}) {const [falhou,setFalhou]=useState(false);useEffect(()=>setFalhou(false),[url]);return url&&!falhou?<img src={url} alt={`Prévia: ${label}`} onError={()=>setFalhou(true)}/>:<span>{falhou?'Imagem indisponível · nome institucional preservado':'Sem imagem · alternativa com nome institucional'}</span>}
