begin isolation level repeatable read read only;
select 'rotinas' secao,coalesce(jsonb_agg(jsonb_build_object('assinatura',n.nspname||'.'||p.oid::regprocedure::text,'owner',pg_get_userbyid(p.proowner),'security_definer',p.prosecdef,'authenticated_execute',has_function_privilege('authenticated',p.oid,'EXECUTE'),'service_role_execute',has_function_privilege('service_role',p.oid,'EXECUTE'),'public_execute',exists(select 1 from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))a where a.grantee=0 and a.privilege_type='EXECUTE'),'referencia_entradas',p.prosrc~*'entradas_caixa','escreve_entradas',p.prosrc~*'(insert[[:space:]]+into|update|delete[[:space:]]+from)[[:space:]]+(public[.])?entradas_caixa','escreve_sessoes',p.prosrc~*'(insert[[:space:]]+into|update|delete[[:space:]]+from)[[:space:]]+(public[.])?sessoes_caixa','menciona_idempotency',p.prosrc~*'idempotency_key','corpo_md5',md5(p.prosrc)) order by n.nspname,p.proname),'[]') dados from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.prokind='f' and n.nspname in('public','private','financeiro_privado') and p.prosrc~*'(entradas_caixa|sessoes_caixa)'
union all select 'papeis',coalesce(jsonb_agg(jsonb_build_object('papel',rolname,'superuser',rolsuper,'bypassrls',rolbypassrls,'login',rolcanlogin) order by rolname),'[]') from pg_roles where rolname in('authenticated','service_role','postgres','financeiro_api')
union all select 'atividade',jsonb_build_object('momento',transaction_timestamp(),'outras_transacoes',(select count(*) from pg_stat_activity where datname=current_database() and pid<>pg_backend_pid() and xact_start is not null),'preparadas',(select count(*) from pg_prepared_xacts where database=current_database()),'conexoes',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select usename,application_name,state,count(*) quantidade,min(xact_start) inicio_transacao_mais_antiga from pg_stat_activity where datname=current_database() and pid<>pg_backend_pid() group by usename,application_name,state order by usename,application_name,state)x),'cron_relacao',to_regclass('cron.job'),'financeiro_privado_schema',to_regnamespace('financeiro_privado'),'pgrst_schemas_config',current_setting('pgrst.db_schemas',true))
union all select 'grants_sessoes',coalesce(jsonb_agg(jsonb_build_object('role',grantee,'operation',privilege_type) order by grantee,privilege_type),'[]') from information_schema.role_table_grants where table_schema='public' and table_name='sessoes_caixa' and grantee in('authenticated','service_role','postgres');
rollback;
-- Abrangência dos metadados e proteção moderna existente.
begin isolation level repeatable read read only;
select jsonb_build_object('momento',transaction_timestamp(),'usuario_sql',current_user,'stats_completos',pg_has_role(current_user,'pg_read_all_stats','USAGE'),'monitor',pg_has_role(current_user,'pg_monitor','USAGE'),'trigger_bloqueio_recebimento',(select coalesce(jsonb_agg(jsonb_build_object('tabela',t.tgrelid::regclass::text,'trigger',t.tgname,'enabled',t.tgenabled,'definicao',pg_get_triggerdef(t.oid))),'[]') from pg_trigger t where t.tgfoid=to_regprocedure('private.financeiro_bloquear_recebimento_sessao_legada()') and not t.tgisinternal),'locks_escrita_outros',(select coalesce(jsonb_agg(jsonb_build_object('pid',l.pid,'relacao',l.relation::regclass::text,'modo',l.mode,'concedido',l.granted) order by l.pid,l.relation),'[]') from pg_locks l join pg_class c on c.oid=l.relation where l.pid<>pg_backend_pid() and c.relnamespace='public'::regnamespace and c.relname=any(array['entradas_caixa','recebimentos','recebimentos_pagamentos','movimentos_caixa','estornos','estornos_pagamentos','sangrias_caixa','fechamentos_caixa','revisoes_fechamento_caixa','repasses','repasses_itens','ajustes_repasse','aplicacoes_ajuste_repasse','documentos_fiscais','tentativas_documento_fiscal','sessoes_caixa','auditoria','eventos_auditoria_financeira','clinicas','usuarios','usuarios_clinicas']) and l.mode in('RowExclusiveLock','ShareRowExclusiveLock','ExclusiveLock','AccessExclusiveLock')),'old_schema',to_regnamespace('financeiro_privado'),'old_fechar_rpc',to_regprocedure('public.fechar_caixa(uuid,numeric,text)'));
rollback;
