import { test, expect, type Page } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
const url = '/tests/financeiro/recepcao-preview.html'
test.beforeEach(async ({ page }) => {
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort())
})
async function abrir(page: Page, cenario = 'aberto') { await page.goto(`${url}?cenario=${cenario}`); await expect(page.getByRole('heading', { name: 'Caixa da recepção' })).toBeVisible() }
async function split(page: Page) {
  await page.getByRole('button', { name: '＋ Receber pagamento' }).click()
  await page.getByLabel('Dividir pagamento').check()
  await page.getByLabel('Dinheiro entregue pelo paciente').fill('150,00')
  await page.getByLabel('Conferi o Pix externamente').check()
}
test('composição coerente, proposta opcional, filtro e paginação', async ({ page }) => {
  await abrir(page)
  await expect(page.getByTestId('esperado')).toHaveText(/420,00/)
  await expect(page.getByTestId('recebido')).toHaveText(/900,00/)
  await expect(page.getByText('A receber hoje · proposta')).toHaveCount(0)
  await page.getByRole('button', { name: 'Próxima', exact: true }).click()
  await expect(page.getByText('Maria Exemplo')).toBeVisible()
  await page.getByLabel('Buscar movimentação').fill('Carla')
  await expect(page.getByText('Carla Exemplo')).toBeVisible()
  await expect(page.getByText('Pedro Exemplo')).toHaveCount(0)
})
test('split integral, troco, confirmação única e falha de impressão', async ({ page }) => {
  await abrir(page); await split(page)
  await expect(page.getByTestId('troco')).toHaveText(/50,00/)
  const enviar = page.getByRole('button', { name: /Registrar R\$.*220,00/ })
  // Dois eventos no mesmo ciclo devem passar pela trava antes de qualquer resposta.
  await enviar.evaluate((el: HTMLButtonElement) => { el.click(); el.click() })
  await expect(page.getByText('Recebimento de R$', { exact: false })).toHaveCount(0)
  await expect(page.getByText(/Recebimento de.*220,00 confirmado pelo serviço sintético/)).toBeVisible()
  await page.getByRole('button', { name: 'Imprimir recibo demonstrativo' }).click()
  await expect(page.getByText(/Impressão não concluída/)).toBeVisible()
  await page.getByRole('button', { name: 'Tentar impressão novamente' }).click()
  await expect(page.getByText(/Reimpressão simulada concluída/)).toBeVisible()
  await page.getByRole('button', { name: 'Concluir demonstração' }).click()
  await expect(page.getByTestId('recebido')).toHaveText(/1.120,00/)
  await expect(page.getByTestId('esperado')).toHaveText(/520,00/)
  await expect(page.getByText('Valor bruto de toda a sessão.')).toBeVisible()
})
test('não permite parcial, dinheiro insuficiente ou valor inválido', async ({ page }) => {
  await abrir(page); await split(page)
  await page.getByLabel('Pix no pagamento').fill('110,00')
  await page.getByRole('button', { name: /Registrar/ }).click()
  await expect(page.getByText(/Distribua o valor integral/)).toBeVisible()
  await page.getByLabel('Pix no pagamento').fill('120,00')
  await page.getByLabel('Dinheiro entregue pelo paciente').fill('99,00')
  await page.getByRole('button', { name: /Registrar/ }).click()
  await expect(page.getByText(/dinheiro entregue suficiente/)).toBeVisible()
  await page.getByLabel('Dinheiro entregue pelo paciente').fill('150,00')
  await page.getByLabel('Crédito no pagamento').fill('texto')
  await page.getByRole('button', { name: /Registrar/ }).click()
  await expect(page.getByText('Valor monetário inválido.')).toBeVisible()
})
test('falha mantém formulário, reenvio não confirma cedo', async ({ page }) => {
  await abrir(page); await page.getByText('Cenários de demonstração').click(); await page.getByLabel('Simular falha do serviço').check(); await split(page)
  await page.getByRole('button', { name: /Registrar/ }).click()
  await expect(page.getByText(/Falha simulada do serviço/)).toBeVisible()
  await expect(page.getByLabel('Dinheiro no pagamento')).toHaveValue('100,00')
  await expect(page.getByText(/Recebimento de.*confirmado pelo serviço/)).toHaveCount(0)
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(page.getByTestId('recebido')).toHaveText(/900,00/)
})
test('mudança de clínica invalida formulário e resposta em trânsito', async ({ page }) => {
  await abrir(page); await split(page)
  await page.getByRole('button', { name: /Registrar/ }).click()
  await page.getByRole('button', { name: 'Simular mudança de clínica durante o formulário' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText('03/10/2026 · Clínica Brotas')).toBeVisible()
  await page.waitForTimeout(750)
  await expect(page.getByTestId('recebido')).toHaveText(/900,00/)
  await expect(page.getByText(/Recebimento de.*confirmado pelo serviço/)).toHaveCount(0)
})
test('abertura sem preenchimento histórico, contexto explícito e valor zero', async ({ page }) => {
  await abrir(page, 'fechado')
  await expect(page.getByLabel('Fundo inicial contado')).toHaveValue('')
  await page.getByLabel('Fundo inicial contado').fill('0,00')
  await page.getByLabel(/Confirmo Clínica Ipupiara/).check()
  await page.getByRole('button', { name: /Abrir caixa com/ }).click()
  await expect(page.getByText(/Abertura confirmada pelo serviço sintético/)).toBeVisible()
  await expect(page.getByTestId('esperado')).toHaveText(/0,00/)
})
test('divergência justificada, registros eletrônicos e aprovação separada', async ({ page }) => {
  await abrir(page, 'divergencia'); await page.getByRole('button', { name: 'Conferir fechamento' }).click()
  await page.getByRole('button', { name: 'Revisar contagem' }).click()
  await expect(page.getByText(/Conferência externa não informada/)).toBeVisible()
  await expect(page.getByText(/-R\$.*2,00/)).toBeVisible()
  await page.getByLabel('Justificativa da diferença').fill('Diferença identificada na contagem demonstrativa.')
  await page.getByRole('button', { name: 'Enviar para aprovação' }).click()
  await expect(page.getByText(/Contagem enviada para aprovação no serviço sintético/).last()).toBeVisible()
  await page.getByRole('button', { name: 'Concluir demonstração' }).click()
  await expect(page.getByText('Somente a proprietária pode aprovar ou devolver.')).toBeVisible()
})
test('sangria não reduz saldo solicitado; suprimento reduzido à sua natureza', async ({ page }) => {
  await abrir(page)
  await page.getByText('Outras ações ▾').click(); await page.getByRole('button', { name: 'Solicitar sangria', exact: true }).click()
  await page.getByLabel('Valor', { exact: true }).fill('100,00'); await page.getByLabel('Motivo', { exact: true }).fill('Guarda do dinheiro')
  await page.getByRole('button', { name: 'Revisar dados' }).click(); await page.getByRole('button', { name: 'Confirmar simulação' }).click()
  await expect(page.getByText(/Sangria solicitada:.*Aguardando aprovação/).last()).toBeVisible()
  await page.getByRole('button', { name: 'Concluir demonstração' }).click()
  await expect(page.getByTestId('esperado')).toHaveText(/420,00/)
  await page.getByText('Outras ações ▾').click(); await page.getByRole('button', { name: 'Suprimento', exact: true }).click()
  await page.getByLabel('Valor', { exact: true }).fill('50,00'); await page.getByLabel('Motivo', { exact: true }).fill('Reforço de troco')
  await page.getByRole('button', { name: 'Revisar dados' }).click(); await page.getByRole('button', { name: 'Confirmar simulação' }).click()
  await expect(page.getByText(/Suprimento de.*confirmado pelo serviço/).last()).toBeVisible(); await page.getByRole('button', { name: 'Concluir demonstração' }).click()
  await expect(page.getByTestId('esperado')).toHaveText(/470,00/); await expect(page.getByTestId('recebido')).toHaveText(/900,00/)
})
test('estorno de outra sessão exige saldo e motivo, preserva original', async ({ page }) => {
  await abrir(page); await page.getByRole('tab', { name: 'Estornos', exact: true }).click()
  await page.getByRole('button', { name: 'Solicitar estorno', exact: true }).click()
  await page.getByLabel('Valor a estornar em dinheiro').fill('51,00'); await page.getByLabel('Motivo', { exact: true }).fill('Correção solicitada')
  await page.getByRole('button', { name: 'Revisar dados' }).click(); await expect(page.getByText(/Saldo elegível em dinheiro/)).toBeVisible()
  await page.getByLabel('Valor a estornar em dinheiro').fill('50,00'); await page.getByRole('button', { name: 'Revisar dados' }).click(); await page.getByRole('button', { name: 'Confirmar simulação' }).click()
  await expect(page.getByText(/Estorno solicitado:.*Sem devolução/).last()).toBeVisible()
})
test('teclado, foco contido, retorno e Fiscal indisponível', async ({ page }) => {
  await abrir(page)
  await page.getByRole('tab', { name: 'Caixa', exact: true }).focus(); await page.keyboard.press('ArrowRight'); await expect(page.getByRole('tab', { name: 'Estornos', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowRight'); await expect(page.getByText('Emissão externa não configurada')).toBeVisible(); await expect(page.getByRole('button', { name: /Emitir externamente/ })).toBeDisabled()
  await page.getByRole('tab', { name: 'Caixa', exact: true }).click(); const origem = page.getByRole('button', { name: '＋ Receber pagamento' }); await origem.click()
  await page.keyboard.press('Shift+Tab'); await expect(page.getByRole('button', { name: /Simular mudança de clínica durante o formulário/ })).toBeFocused()
  await page.keyboard.press('Tab'); await expect(page.getByRole('button', { name: 'Fechar', exact: true })).toBeFocused()
  await page.keyboard.press('Escape'); await expect(origem).toBeFocused()
})
test('estados separados de zero, erro, carregamento, legado e falta de permissão', async ({ page }) => {
  for (const [cenario, texto] of [['vazio', 'Nenhuma movimentação'], ['erro', 'Não foi possível carregar o caixa'], ['carregando', 'Carregando dados demonstrativos…'], ['legado', 'Caixa legado preservado'], ['permissao', 'Acesso restrito']]) {
    await abrir(page, cenario); await expect(page.getByText(texto, { exact: true })).toBeVisible()
    if (cenario !== 'vazio') await expect(page.getByTestId('esperado')).toHaveCount(0)
  }
})
test('capturas, temas, telas estreitas e rodapé no fluxo normal', async ({ page }, info) => {
  await mkdir('scratch/caixa-recepcao', { recursive: true }); await abrir(page)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `scratch/caixa-recepcao/${info.project.name}-aberto.png`, fullPage: true })
  await split(page); await page.locator('.cp-fluxo').evaluate(el => { el.scrollTop = 0 }); await page.screenshot({ path: `scratch/caixa-recepcao/${info.project.name}-receber.png` })
  await page.getByRole('button', { name: /Registrar/ }).scrollIntoViewIfNeeded()
  const botao = await page.getByRole('button', { name: /Registrar/ }).boundingBox(); expect(botao!.y + botao!.height).toBeLessThanOrEqual(info.project.use.viewport!.height)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /Ativar modo/i }).click()
  await page.screenshot({ path: `scratch/caixa-recepcao/${info.project.name}-escuro.png`, fullPage: true })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.goto(`${url}?cenario=fechado`); await page.screenshot({ path: `scratch/caixa-recepcao/${info.project.name}-abertura.png`, fullPage: true })
  await page.goto(`${url}?cenario=divergencia`); await page.getByRole('button', { name: 'Conferir fechamento' }).click(); await page.getByRole('button', { name: 'Revisar contagem' }).click()
  await page.screenshot({ path: `scratch/caixa-recepcao/${info.project.name}-fechamento.png` })
})

test('proprietária decide estorno, não solicita; caixa atual preserva original', async ({ page }) => {
  await abrir(page); await page.getByText('Cenários de demonstração').click(); await page.getByLabel('Perfil simulado').selectOption('proprietaria')
  await page.getByRole('tab', { name: 'Estornos', exact: true }).click(); await expect(page.getByRole('button', { name: 'Solicitar estorno', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Revisar solicitação' }).click(); await expect(page.getByLabel('Valor a estornar em dinheiro')).toBeDisabled()
  await page.getByRole('button', { name: 'Revisar dados' }).click(); await page.getByRole('button', { name: 'Confirmar simulação' }).click()
  await expect(page.getByText(/Estorno EST003 efetivado no caixa atual/).last()).toBeVisible(); await page.getByRole('button', { name: 'Concluir demonstração' }).click()
  await expect(page.getByText('R$ 50,00 · efetivado · 03/10/2026')).toBeVisible()
  await page.getByRole('tab', { name: 'Caixa', exact: true }).click(); await expect(page.getByTestId('esperado')).toHaveText(/370,00/); await expect(page.getByTestId('recebido')).toHaveText(/900,00/)
})

test('aprovação e devolução de fechamento seguem perfil, sem nova abertura', async ({ page }) => {
  for (const decisao of ['aprovar', 'devolver']) {
    await abrir(page, 'aprovacao'); await page.getByText('Cenários de demonstração').click(); await page.getByLabel('Perfil simulado').selectOption('proprietaria')
    await page.getByRole('button', { name: 'Revisar fechamento', exact: true }).click(); await page.getByLabel('Decisão da proprietária').selectOption(decisao)
    if (decisao === 'devolver') await page.getByLabel('Observação / orientação').fill('Recontar as cédulas.')
    await page.getByRole('button', { name: 'Confirmar decisão' }).click(); await expect(page.getByText(/Fechamento (aprovado|devolvido para correção) no serviço sintético/).last()).toBeVisible()
    await page.getByRole('button', { name: 'Concluir demonstração' }).click()
    if (decisao === 'aprovar') await expect(page.getByLabel('Fundo inicial contado')).toHaveValue('')
    else await expect(page.getByText('Contagem devolvida pela proprietária')).toBeVisible()
  }
})

test('celulares 360 e 430, clínica alternativa, proposta identificada e detalhe', async ({ page }, info) => {
  if (info.project.name !== 'mobile') return
  for (const width of [360, 430]) {
    await page.setViewportSize({ width, height: 844 }); await page.goto(`${url}?clinica=brotas&proposta=1`)
    await expect(page.getByText('A receber hoje · proposta')).toBeVisible()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `scratch/caixa-recepcao/mobile-${width}-brotas-proposta.png`, fullPage: true })
    await page.getByRole('button', { name: 'Detalhes de Pedro Exemplo' }).click(); await expect(page.getByRole('heading', { name: 'Detalhes da movimentação' })).toBeVisible()
    await page.keyboard.press('Escape'); await page.getByRole('tab', { name: 'Fiscal', exact: true }).click()
    await page.screenshot({ path: `scratch/caixa-recepcao/mobile-${width}-fiscal.png`, fullPage: true })
  }
})
